### ISSUE TITLE
Add Device Integration page

### ISSUE THREAD

**Issue by iskerrett** [FlowFuse/website#1118]
### Description

We need to create a page that documents how hardware vendors can pre-load our device agent on to their hardware platform.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by MarianRaphael** [comment]
https://docs.google.com/document/d/16A98K6eQyJhoKc5H5oO7ZfAZOxRSZQqZHMXwWmjPVm0/edit?usp=sharing

**Comment by Yndira-FlowForge** [comment]
Hi @MarianRaphael in the document you shared, there's the first part (only text), and the second part: an image as an idea for the layout. The image has more/different content. Which one should I use as a guide? In case is the text, for certification it only says: book a meeting, this should link to /book-demo, am I correct?

**Comment by Yndira-FlowForge** [comment]
Here's a proposal using the content from the first section of the document

![Certify your Hardware](https://github.com/FlowFuse/website/assets/129537638/88df320e-d039-4a99-a9b0-cbd2340b3bf9)

**Comment by MarianRaphael** [comment]
Design looks great!

**Comment by Yndira-FlowForge** [comment]
Is this going to be under "product"?
