### ISSUE TITLE
Professional services website page

### ISSUE THREAD

**Issue by zackwasli** [FlowFuse/website#1148]
### Description

The Sales and Customer Success teams are often asked whether FlowFuse provides Professional Services or flow engineering. It may be helpful to have a page on the website that mentions this capability and that it is discretionary, based on significant commercial engagement, a strategic project, or new vertical discovery, etc.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
cc @Yndira-FlowForge

**Comment by iskerrett** [comment]
We can certainly create a page. Do we have a definition of what professional service we offer?

**Comment by zackwasli** [comment]
This is an rough draft outline that ZJ and I started. Would love to get feedback from @robmarcer and @iskerrett 

https://docs.google.com/document/d/1WdRd2uPwjtxFQsVoib0ZFHxbvXWqsxYUx4wRu4-UMZs/edit

**Comment by Yndira-FlowForge** [comment]
Hi, this is the mockup I shared today during the marketing meeting:

![Image](https://github.com/FlowFuse/website/assets/129537638/b4f24b86-7211-42a6-b3b3-ab4b964fdffa)

We'll need a new HubSpot form, and @iskerrett said he could help with that. Additionally, we need to replace the placeholder text, and I'll make some adjustments to the first image to include some Node-RED flows.

I'll start working on the development of the page, and I'll add the form and the text once we have them.

**Comment by iskerrett** [comment]
For under Professional Services title I would suggest the following:
FlowFuse partner with our customers to ensure their successful deployment of FlowFuse and Node-RED. Discover our professional service offerings.

**Comment by iskerrett** [comment]
For under Contact Us, how about:
Reach out to discuss how FlowFuse expects can help with your FlowFuse and Node-RED projects.
