### ISSUE TITLE
Mobile Usability issues

### ISSUE THREAD

**Issue by Yndira-FlowForge** [FlowFuse/website#1186]
### Description

We've received the following message from Google Search Console:

> Mobile Usability issues detected in [flowfuse.com](http://flowfuse.com/)
> 
> To the owner of [flowfuse.com](http://flowfuse.com/):
> 
> Search Console has identified that your site is affected by 2 Mobile Usability issue(s). The following issues were found on your site.
> 
> Top Issues
> 
> Clickable elements too close together
> Text too small to read
> We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.

Both issues related to the /about page.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-FlowForge** [comment]
@ZJvandeWeg when I click on the "Fix Mobile Usability issues" it takes me to:
<img width="600" alt="Screenshot 2023-09-29 at 14 32 49" src="https://github.com/FlowFuse/website/assets/129537638/9b72eb64-5d69-4fdb-ba1b-d76365d82084">
Does it provide any more information? Like which elements are the ones with issues?

**Comment by ZJvandeWeg** [comment]
@Yndira-FlowForge It links to: https://support.google.com/webmasters/answer/9063469#small_font_size

**Comment by joepavitt** [comment]
Text too small to read problem isn't on the website, but `/api` ([console](https://search.google.com/u/1/search-console/mobile-usability/drilldown?resource_id=sc-domain%3Aflowforge.com&item_key=CAw&hl=en))

<img width="937" alt="Screenshot 2023-09-29 at 16 09 15" src="https://github.com/FlowFuse/website/assets/99246719/185c3d0c-87d8-4fe6-9202-155fd0c9b335">

**Comment by joepavitt** [comment]
Clickable elements too close together are also on that same page: https://search.google.com/u/1/search-console/mobile-usability/drilldown?resource_id=sc-domain%3Aflowforge.com&item_key=CAs&hl=en

**Comment by joepavitt** [comment]
Noticing that I only have access to `flowforge.com` though, rather than `flowfuse.com`, so my data is likely inaccurate

**Comment by joepavitt** [comment]
yep, just verified with @Yndira-FlowForge as she sent me an updated report link, I don't have access to the console in order to dive into what is causing this

**Comment by Yndira-FlowForge** [comment]
Hi @ZJvandeWeg could you please give me access to the console?

**Comment by Yndira-FlowForge** [comment]
I ran a live test from the console and [this was the result](https://search.google.com/test/mobile-friendly/result?id=-8uLNlCUmg7LCsu2YugORQ): 
<img width="1250" alt="Screenshot 2023-10-02 at 11 30 09" src="https://github.com/FlowFuse/website/assets/129537638/9afa6c49-5805-4c83-bbc7-5ffe964233c9">

So, I've clicked on 'validate fix' to see what happens... It says this could take days.

I checked the documentation, and it states that 60% of the fonts should be >12px, and all the fonts on that page are 16px or larger. As for the spacing, I couldn't find anything suspicious on that page—perhaps the footer. I'll work on improving it to see how it goes.

**Comment by Yndira-FlowForge** [comment]
Google says the issues are fixed now:

1. [Clickable elements too close together](https://notifications.google.com/g/p/ANiao5qimsvqdJYahnCix_EE6PIJ7VC1j3UAUERijw32lUMRAfLlqVF-BnZqlc9QW0c8cP5mcOgXTkt5MFoKioKMsxXLnicFYjcUXArEjUdygq6Q3CpvyMTOh31wyvbI4U72GP4IRrTI4H81RII_P40FAAwDZ4UpNqNwNVAse_P_UDs8EyLcLbZa1v5sHoqr8um5vNdYQhkivWcTnN-UYivA9NDGZX-Q8x9MLzdq2qxpI4RNI6iG1eTiMYDP4cLLild2tlVutqUr4frJhhmGpbcwTO2ApAnq1D1M1NGLPcb1uJjSdoVLk7PVAJsrAtfUZw-WoDBuapXDbcJ7O6al7STXwYKlYLPMR08bx__esJHuFNjDz8MN04vJWvWonxBKBVtUno-3BCX36A-Rht66obQJJYDs-PYmtm_qf_UapxhkA-eHcR8fddV_b3O798pFlKeBpkWf7arBtek46fzJSG6ajRcontBNJGm7_Q)
<img width="650" alt="Screenshot 2023-10-03 at 08 55 36" src="https://github.com/FlowFuse/website/assets/129537638/53f27b68-8373-45b8-9434-be5f1074cdc8">


2. [Text too small to read](https://notifications.google.com/g/p/ANiao5r5lhBqSDyfdLmrSKdi2AD2UgxguDRE5PgQKMMqUqMlBUBnR3QSrJjER3YuYxafeBslfnsgDwZXG8YPU5IPOpU8J_QibP9FyaKN-PSZfPUCtb1qrRsaLTQjlpgvj0F1vN0YKc54sXoTw9xIWYW8xVttFokoF9gfvEqOMSnzymTTu2vbvYGeRI4erg-AwcSF1mQNz36kbzS4BvBXBIHAoVPgKc7Y5alcG8wVnTzD5274qJlFrw7W9TTEqZcLnf-W_aG6A-cuJ5TDf5eBxho9EyQQISFtggxTXLClFAvAAEyR1QTxoVKjTH3uA4_3mugxFUVHd5jIgXP4FMT0sJJuVRGimUooCFwhuF0fQDw2nzmGQV6nhLjwfkVekZSwV2JgV80XOz3DaVCN6J34QOOwcZdcYWB661-Km69l6Br3OmVO5d18CynO9iKFQpU4MYu8Ss1gVOwtmRvd1Ogu1Ts48w66loE-HAsX)
<img width="645" alt="Screenshot 2023-10-03 at 08 58 48" src="https://github.com/FlowFuse/website/assets/129537638/ea021716-1afd-4676-99a5-cd47de4ee09b">
