### ISSUE TITLE
Graphic for "Securing your Dashboard"

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/website#1190]
### Description

**Considerations:**
- In a blog post that accompanies a video

**Inspirations:**
-  https://flowfuse.com/img/db-notebook-tile-E_jQBPxMM8-560.avif with a "secure" shield or padlock (in FF colours) infering secure access

**Comment by Yndira-FlowForge** [comment]
what do you think?

![Securing-your-Dashboard-2](https://github.com/FlowFuse/website/assets/129537638/c2a167b1-1060-4976-9338-4520b7dd3ab5)

**Comment by Steve-Mcl** [comment]
Really really good. Thank you.

**Comment by Yndira-FlowForge** [comment]
https://www.youtube.com/watch?v=pCYzJGVkG8s
