### ISSUE TITLE
Adding private custom nodes in FlowFuse

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/website#1195]
### Description

**Considerations:**
- Blog tile for: https://github.com/FlowFuse/website/pull/1177/files

**Inspirations:**
- Verdaccio logo?
- Node-RED logo
- Extensibility
- Protection of private code?

**Comment by Yndira-FlowForge** [comment]
Would this make sense?
![How-to-Use-Custom-Nodes-in-FlowFuse](https://github.com/FlowFuse/website/assets/129537638/42b9feb6-e548-4cee-87ec-24daaae3aade)

**Comment by ZJvandeWeg** [comment]
The word Private is missing before custom Nodes. Can you add it?

**Comment by Yndira-FlowForge** [comment]
![How-to-Use-Custom-Nodes-in-FlowFuse](https://github.com/FlowFuse/website/assets/129537638/0dae7e21-c905-4953-80b4-282d6cbff51f)
