### ISSUE TITLE
October webinar graphic

### ISSUE THREAD

**Issue by iskerrett** [FlowFuse/website#1203]
### Description

The October webinar is about Dashboard 2.0.  

See PR #1202 for the details.

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett here it is. Is the info correct? 

![Image](https://github.com/FlowFuse/website/assets/129537638/5449ab6f-6348-4d03-bb28-211c951610fa)

**Comment by iskerrett** [comment]
Yes it is.

**Comment by Yndira-FlowForge** [comment]
Great! I'll add it to the pr
