### ISSUE TITLE
Swap logos on the front page

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/website#1220]
### Description

Logos to add:
- Arduino (Requires approval from their side, please just create a PR at first)
- Bosch (now we're a partner cc @MarianRaphael )

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
cc @iskerrett @Yndira-FlowForge

**Comment by Yndira-FlowForge** [comment]
Is this order ok?
<img width="1440" alt="Screenshot 2023-10-10 at 08 49 39" src="https://github.com/FlowFuse/website/assets/129537638/79508e6d-5531-4d23-8ccd-7f239169751c">

**Comment by ZJvandeWeg** [comment]
@Yndira-FlowForge Arduino is somewhat small, Leclanche is the first one my eyes saw, so can we swamp Arduino and leclanche?

**Comment by Yndira-FlowForge** [comment]
> Arduino is somewhat small, Leclanche is the first one my eyes saw, so can we swamp Arduino and leclanche?
Sure, it would be like this
<img width="1440" alt="Screenshot 2023-10-10 at 12 33 52" src="https://github.com/FlowFuse/website/assets/129537638/66d5ca1a-c044-4f83-b3c2-d523733151ac">
