### ISSUE TITLE
Graphic to accompany blog post on "Monitoring your devices using Dashboard 2"

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/website#1239]
### Description

**Considerations:**
- Image to be used in video and blog content
- Trying to convey devices (running node-red, configured by FlowForge) inside a users network feeding status to a cloud FlowFuse and a dashboard representing the status data the devices are transmitting.

**Inspirations:**

Based on this layout (but much prettier and in FF styles/hues/iconography)
![image](https://github.com/FlowFuse/website/assets/44235289/727ec897-ddb0-41bb-9be7-0fc9f23c8555)

If you can stylise the wires with binary, then `01000110 01101100 01101111 01110111 01000110 01110101 01110011 01100101`  represents the word "FlowFuse"

The top section (external) could be styled in the usual FF colours

The bottom section (internal) could have an "industrial" or "internal" feel?

The lower section could have a 3rd device but in reduced opacity or dotted outline to signify additional/future addition labelled "Device n"

<br>

Below is a sample of the dashboard that will be built in the work - perhaps this can be used in constructing the "Dashboard" part of the graphic above? (not necessary - could be one of the more beautiful images already created for Dashboard content but here it is anyway)

![image](https://github.com/FlowFuse/website/assets/44235289/80b5ec22-94b6-4fc0-bbcb-f02d0867ffa3)

**Comment by Yndira-FlowForge** [comment]
Added to [this video](https://drive.google.com/open?id=1uoyhm4QOcWrfrgyGe1bo81NFKPkUh7sL&usp=drive_fs)
