### ISSUE TITLE
FlowFuse Blueprint Image

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/website#1246]
### Related Issue

https://github.com/FlowFuse/website/pull/1245

### Description

**Considerations:**
Image for FlowFuse Blueprints Article

**Comment by Yndira-FlowForge** [comment]
Hi @MarianRaphael wdyt?


![Image](https://github.com/FlowFuse/website/assets/129537638/4d5b8b77-d8e2-4d8e-94d6-6e66f88e8922)
