### ISSUE TITLE
FlowFuse Blueprint Library - Page

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/website#1256]
The idea is to have a page on the website to present  our "blueprints," allowing users to search for specific solutions before signing up and to improve our SEO

## Examples

Node-RED Library: https://flows.nodered.org/
Tulip Library: https://tulip.co/library/

**Comment by iskerrett** [comment]
For each Blueprint:
Title/Name
Purpose
WHo would use it
How to use it
Screenshot
