### ISSUE TITLE
"certified nodes" list page

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/website#1257]
### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
Split out from: https://github.com/FlowFuse/website/issues/1256

**Comment by Yndira-FlowForge** [comment]
@ZJvandeWeg I need some context for this issue.

I came across this list: https://docs.google.com/spreadsheets/d/1gMXwR-30guVxmzSxfORq1TEW5RuZfH3JcDnb_LAibL0/edit#gid=0

- Could you clarify what should be included on the page?
- Is it meant to be just a list? 
- Do you have an example of a similar page that I can use for reference?
- Where should we place it in the menu?
- Should we dedicate a whole page to this list, or could we incorporate it as a section in the 'Why FlowFuse' page? We could briefly explain the meaning of "certified nodes" and link to our documentation for the list.

**Comment by ZJvandeWeg** [comment]
Let's include all the green lines from the list at first.

I think a list and a page per package would be great, though as first iteration a list will suffice. Please take a look at their flows.nodered.org pages for reference.

> Where should we place it in the menu?

Don't know. We should iterate there right after, our menus are messy

Should we dedicate a whole page to this list, or could we incorporate it as a section in the 'Why FlowFuse' page?

New page imo, linked from the why FF.

We could briefly explain the meaning of "certified nodes" and link to our documentation for the list.

Yes please!
