### ISSUE TITLE
MES Buy vs Build Art Request

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1258]
### Related Issue

#

### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website? 

This will be for Blog content.

You can see the article [here](https://github.com/FlowFuse/website/blob/mes-build-vs-buy-article/src/blog/2023/10/mes-build-buy.md): 

**Inspirations:**
- [Image 1](https://akfpartners.com//uploads/blog/buil_vs_buy_header.jpg) 
-  [Image 2 ](https://learnosity.com/wp-content/uploads/2016/05/build-vs-buy-2.jpg)

**Comment by gdziuba** [comment]
Related: https://github.com/FlowFuse/content/issues/135

**Comment by Yndira-FlowForge** [comment]
Hi @gdziuba how about this one?


![Image](https://github.com/FlowFuse/website/assets/129537638/a258d9b6-06bb-4dc8-8f79-b1116fd10ec2)
