### ISSUE TITLE
New LinkedIn profile banner with the new messaging

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/website#1269]
### Description

- New LinkedIn profile banner with our new messaging

**Inspirations:**
- Current Banner

**Comment by Yndira-FlowForge** [comment]
Hi @MarianRaphael I've updated all the social media banners with the new messaging. They're all [here](https://drive.google.com/open?id=1rP04T2K8QszZxGRt16tM7ahuVbNlQYTs&usp=drive_fs).

Do you need a different one?
