### ISSUE TITLE
Image for blog article about "Citizen Developers"

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/website#1271]
### Related Issue

https://github.com/FlowFuse/website/pull/1270

### Description

**Considerations:**
Image for blog article about "Citizen Developers"

**Inspirations:**
- https://quixy.com/wp-content/uploads/2020/03/blog_-rise-citizen-developer.png

**Comment by Yndira-FlowForge** [comment]
Hi @MarianRaphael how about this one?


![Image](https://github.com/FlowFuse/website/assets/129537638/f321a39a-07af-430d-b69b-bb80f2fc5014)
