### ISSUE TITLE
Image for Certified Nodes Blog Article

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/website#1283]
### Description

**Considerations:**
Image for Certified Nodes Blog Article
https://github.com/FlowFuse/website/blob/Certified-Nodes-Article/src/blog/2023/10/certified-nodes.md

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-FlowForge** [comment]
Hi @MarianRaphael, here's a couple of options:


![Image](https://github.com/FlowFuse/website/assets/129537638/bd0326dd-23db-4ae6-b2d7-984a9697711c)



![Image](https://github.com/FlowFuse/website/assets/129537638/428a8df0-ebc5-4745-a099-bd4a20ff292d)

**Comment by MarianRaphael** [comment]
@Yndira-FlowForge Thank you!! 
Get well soon!
