### ISSUE TITLE
Image for AI Use Cases article

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/website#1292]
### Related Issue

 https://github.com/FlowFuse/website/pull/1291

### Description

Image for the AI Use Cases blog article

Planned for 07/11

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-FlowForge** [comment]
@MarianRaphael I just added it to the PR

![Image](https://github.com/FlowFuse/website/assets/129537638/832a32f6-5235-48e0-b012-dbeec556e06c)
