### ISSUE TITLE
Blog Art - Node-Red Builder a GPT (Alpha) by FlowFuse

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1320]
### Related Issue

https://github.com/FlowFuse/website/pull/1319

### Description

**Considerations:**
- This will be blog art.  I want to display the fusion between ChatGPT, Node-RED, and FlowFuse.

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-FlowForge** [comment]
Hi @gdziuba 
![Node-Red-Builder-a-GPT-(Alpha)-by-FlowFuse](https://github.com/FlowFuse/website/assets/129537638/c0d48401-18b9-4482-922b-437e66beb2cc)

I already added it to your PR 😉
