### ISSUE TITLE
A graphic for FlowFuse repository on socials and tag lists

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/website#1322]
### Related Issue

https://github.com/FlowFuse/flowfuse/issues/3059

### Description

**Considerations:**
- This image will be seen when users are browsing topics on GitHub 
   - example: Scroll [this list of `low-code`](https://github.com/topics/low-code) projects - note how the better, more prominent entries have a graphic that offers some insight into their offering.
- This image will be seen when a link to our repository is made on socials
   - This is described here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview

**Inspirations:**
- See [this comment](https://github.com/FlowFuse/flowfuse/issues/3059#issuecomment-1812724084)
- Checkout this list to see what works for others: https://github.com/topics/low-code-development-platform
- and this list: https://github.com/topics/low-code
- Essentially, a graphic that attracts users to our platform, makes it stand out, offers some graphical notion of what we offer.

**Comment by Yndira-FlowForge** [comment]
Hi @Steve-Mcl here it is 😃  

![Image](https://github.com/FlowFuse/website/assets/129537638/3b917056-e9b5-4541-bd03-028cc8ab983a)

**Comment by Steve-Mcl** [comment]
Thanks @Yndira-FlowForge - perfect.
