### ISSUE TITLE
ChatGPT AI Assistant Blog Art

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1325]
### Related Issue

1324

https://github.com/FlowFuse/website/pull/1324

### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

Blog art.  AI Assistant.  Differs from ChatGPT GPT

![Screenshot 2023-11-16 125737](https://github.com/FlowFuse/website/assets/8887166/1ff86b0c-26fc-4578-929f-2ec9233165f1)

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-FlowForge** [comment]
Hi @gdziuba here it is


![Image](https://github.com/FlowFuse/website/assets/129537638/4fd98089-6738-40b1-95a0-87c27f9697b4)
