### ISSUE TITLE
Blog header image for Device Agent on Balena.io

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/website#1328]
### Related Issue

#1327

### Description

**Considerations:**
-  blog post, social media image

**Inspirations:**
- SVG balena.io logo https://assets-global.website-files.com/636ab6ba0e1bd250e3aaedaf/636e155e93894cd4d030c4d7_balena_logo_dark.svg

**Comment by Yndira-FlowForge** [comment]
Hi @hardillb here it is


![Image](https://github.com/FlowFuse/website/assets/129537638/b8625473-2c2c-4928-b46a-6e05a0e3f9ff)

**Comment by hardillb** [comment]
Thanks @Yndira-FlowForge
