### ISSUE TITLE
Documentation for Sending API Calls to remote instances

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1367]
### Description

Sending API calls to FF hosted instances is pretty straight forward, but it may be a little confusing for someone to do the same on a remote instance (device). Add additional documentation.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Hasmin-AC** [comment]
included here https://app.flowfuse.com/api/static/index.html
