### ISSUE TITLE
Add ZJs time zone to the book a demo calendar

### ISSUE THREAD

**Issue by Yndira-FlowForge** [FlowFuse/website#1369]
### Description

Our current calendar for booking a demo only shows @zackwasli's availability, we should add's @ZJvandeWeg's too for the potential customer in the UTC+1 time zone.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by zackwasli** [comment]
Oh that's cool that both our times are in the same link, didn't know that was possible. Looks good to me, I was trying to review it for you but can't find how to add that.

**Comment by Yndira-FlowForge** [comment]
@zackwasli I'll add you as a reviewer when I open the PR, for now it's just an issue, that's why you can't find the option to approve or request changes 😉 

So, just to be sure, did you check out the HubSpot configuration and found it all good to go?

**Comment by zackwasli** [comment]
Yes just double checked the HubSpot config and made a few edits, good to go!
