### ISSUE TITLE
December Webinar Artwork

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1380]
### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

Webinar Art Request.

[Firework Simulation that we are integrating into](https://codepen.io/MillerTime/pen/XgpNwb)

https://github.com/FlowFuse/website/pull/1379

**Inspirations:**
- <link here>
- <link here>

**Comment by gdziuba** [comment]
Just saw this @joepavitt It would have been nice to have it done, but it is also now like 4pm for you on a Friday.  It can wait.

**Comment by Yndira-FlowForge** [comment]
Hi @gdziuba 
Here it is 😉 


![Image](https://github.com/FlowFuse/website/assets/129537638/e78e4a7b-e8eb-4e4e-b454-ca1312e66019)
