### ISSUE TITLE
Architecture diagram for PIDD case study

### ISSUE THREAD

**Issue by robmarcer** [FlowFuse/website#1386]
### Description

**Considerations:**
As part of this article, we want to include a diagram of their architecture. - https://docs.google.com/document/d/1WA8cKVu_t9CwD4sOCIOTt_vx04Coiybo2nzxfGlZwn4/edit

The digram should show a central Node-RED instance running on FlowFuse Cloud. That should have 10 (or less if it's earlier to design) Node-RED instances running on edge devices (some Raspberry Pis, some Groov EPICs). Each is linked to a water height sensor, or a pump (which pushes water along the canals), or a well, or a sump (which takes water back out of a field after it's been irrigated).

Maybe we should show some overview of a farming area to make it easier for the reader to understand? I'm open to ideas.

**Comment by robmarcer** [comment]
I'd suggest we chat about this when someone picks up this task.

**Comment by Yndira-FlowForge** [comment]
I'll ping you tomorrow 😉

**Comment by Yndira-FlowForge** [comment]
Here it is @robmarcer

Unless I got something wrong, I think is done!

![Image](https://github.com/FlowFuse/website/assets/129537638/f0b54bbc-545b-42d6-b757-c2f99b703777)

**Comment by robmarcer** [comment]
This is great, I've added it to the article. Thank you!

https://github.com/FlowFuse/website/pull/1441
