### ISSUE TITLE
Replace free-trial main nav button with talk-to-sales button

### ISSUE THREAD

**Issue by Yndira-FlowForge** [FlowFuse/website#1393]
### What are your variants?

**control:** current state, free-trial button, linking to the sign-up page
**test:** instead of sign-up, talk-to-sales.

@ZJvandeWeg @Hasmin-AC we need to decide if we link to `/contact-us` or `/book-demo` for the test variant. @zackwasli [suggested](https://github.com/FlowFuse/customer/issues/93#issuecomment-1833974210) contact-us as he think it would be less of a commitment for the potential customer. I agree, and we now also have a link to `book-demo` in that page. WDYT?

### What does success look like?

 - Higher CTR of the test variant, and increased MQLs through the contact us form.

**Comment by ZJvandeWeg** [comment]
Approved.

**Comment by zackwasli** [comment]
I think we should still have a book a demo button somewhere on our website, but are you saying that the CTA should be consistent on each page?

**Comment by ZJvandeWeg** [comment]
@zackwasli This is about the main nav:

![Screenshot 2023-12-13 at 09 31 36](https://github.com/FlowFuse/website/assets/2529595/3e310fb7-a53d-4313-acf4-9c6c0093d661)

To proposed new way:

![Screenshot 2023-12-13 at 09 32 21](https://github.com/FlowFuse/website/assets/2529595/724dcef6-08e4-4141-ba92-4149d3218e5e)

@Yndira-FlowForge is worried a page can have multiple links to the Contact us and to book a demo. I don't think that's an issue at this stage and we should just make the change
