### ISSUE TITLE
Art Request for Blog - FlowFuse Device Agent  as a Service on Windows

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1396]
### Related Issue

1384

### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

The biggest takeaways are "Auto start on reboot on Windows"  Those are the keywords that we would like to be incorporated in the artwork.

Key is to highlight Windows vs Linux or other platforms.

**Inspirations:**
- <[windows service manager](https://mdsolutions.gallerycdn.vsassets.io/extensions/mdsolutions/windowsservicemanagerwindowsservicemanager/2.0.69/1593698162403/Microsoft.VisualStudio.Services.Icons.Default)>
- <link here>

**Comment by gdziuba** [comment]
Blog - https://github.com/FlowFuse/website/pull/1384

**Comment by Yndira-FlowForge** [comment]
Image added to the PR 😉 
![Auto-start-on-reboot-on-Windows](https://github.com/FlowFuse/website/assets/129537638/7cb52e07-6a0d-4399-92cf-9bf9cecc4874)

**Comment by Yndira-FlowForge** [comment]
Hi @Steve-Mcl let's have a chat so I can better understand the message it should convey. 
Should I use the same title as the article instead?
_"Running the FlowFuse Device Agent as a service on Windows"_

**Comment by Steve-Mcl** [comment]
Yeah, I am good for a chat in the morning @Yndira-FlowForge 

Also, if in the mean time Grey pops in and overrules (more than happy for that) then fine also.

In the mean time, I will put my thinking cap on and be prepared for a chat tomorrow.

**Comment by Steve-Mcl** [comment]
The image you did for the PI + Device agent was a nice layout
https://flowfuse.com/blog/2023/11/raspberry-pi-5-flowfuse-edge-agent/

Perhaps something similar for Windows might be better suited?

Here is my best effort (dont laugh)

![image](https://github.com/FlowFuse/website/assets/44235289/06b70ca7-de26-489b-8add-b4f327a64209)


The wording might still need a little work. 

Perhaps "Run Node-RED with FlowFuse Device Agent as a Windows Service"

**Comment by Yndira-FlowForge** [comment]
Thanks for the reference @Steve-Mcl!!

I did this using your image as guide.
![Image](https://github.com/FlowFuse/website/assets/129537638/1c6c6e87-3f6c-40a0-bdd3-a37c0d3eb01d)

But reading the title, maybe it makes more sense to replace the FlowFuse logo inside the device with the Node-RED one? I did that version too just in case you guys think it works better 😉 

![Image](https://github.com/FlowFuse/website/assets/129537638/8a2c21da-52d8-4432-8268-baab0a580eed)

**Comment by Steve-Mcl** [comment]
I think the 2nd one (with Node-RED inside the service) is fine.

I am not 100% certain I nailed the title. I did suggest an alternative but still not sure 🤔 

Could I be a total pain and ask for a few variations (of the Node-RED version) with different titles so that when Grey comes online later today he has something to chose from?  If that is too much of an ask, then please wait for Grey to evaluate and suggest a final title (Just wanted to see if we can make a jump on it as I seem to remember you saying art requests must be in before end of today?)

#### Alternative versions
* V2a - the Node-RED version (already done)
* V2b - with the title "Run Node-RED as a Windows Service with a FlowFuse Device Agent"
* V2c - with the title "Run your FlowFuse Device Agent as a Windows Service"
* V2d - with the title  "Run and Manage your Node-RED edge instances in a Windows Service"

Thankyoooooo.

**Comment by Yndira-FlowForge** [comment]
I said art requests must be in before the end of next week 😉 
So we can wait until @gdziuba comes online, and I'll only update the artwork once to the final version.

**Comment by Steve-Mcl** [comment]
> I said art requests must be in before the end of next week 😉

🤦‍♂️





> So we can wait until @gdziuba comes online, and I'll only update the artwork once to the final version.

Perfect



Thanks Yndira.

**Comment by Yndira-FlowForge** [comment]
Hi @gdziuba, could you please provide the title so that I can update the image accordingly? Thank you!

**Comment by gdziuba** [comment]
@Yndira-FlowForge 
Title: Running Node-RED as a service on Windows
Subtitle: Step by step guide to run FlowFuse device agent as a Windows service

**Comment by Yndira-FlowForge** [comment]
Here's the updated image
![Running-Node-RED-as-a-service-on-Windows](https://github.com/FlowFuse/website/assets/129537638/0ae71da9-9a82-4c4e-9598-e95134fe3d3f)

**Comment by gdziuba** [comment]
@Yndira-FlowForge Can you remove the subtitle?  Thank you.

**Comment by Yndira-FlowForge** [comment]
There you go 😉 
![Running-Node-RED-as-a-service-on-Windows](https://github.com/FlowFuse/website/assets/129537638/cc811479-0c47-4f17-9958-853868fa3da0)
