### ISSUE TITLE
Blog image for data modeling article

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/website#1418]
### Related Issue

https://github.com/FlowFuse/website/pull/1414

### Description

**Considerations:**
- Blog article image for: "Data Modeling for your Unified Namespace - How to use FlowFuse as your Schema Registry?"

**Comment by Yndira-FlowForge** [comment]
I just added it to the PR 😉 
![uns-data-modeling](https://github.com/FlowFuse/website/assets/129537638/9f767ff2-f337-4fad-bce8-3c6df39e801a)
