### ISSUE TITLE
Create PDF version of WMO case study

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1424]
### Description

Create a PDF document of the case study so that it can be available to download via a form 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
There's two approaches to these issues:
1. Create a PDF manually -- This is probably the best first iteration
2. Create the PDFs automatically

For number 2, which we should probably not pursue right now, I suggest we leverage eleventy and [jsPDF](https://github.com/parallax/jsPDF). So I think we can create extra assets based on data, much like we create the core-nodes doc pages from data: https://www.11ty.dev/docs/pages-from-data/. Than as template language we can take a look at plain JS: https://www.11ty.dev/docs/languages/javascript/

**Comment by Yndira-FlowForge** [comment]
@Hasmin-AC this one is ready.
I'm adding the pdf files in [here](https://drive.google.com/drive/folders/1QXCso0HQPbShrB5_8N0n_sDnIlluUaaI?usp=drive_link)

**Comment by Yndira-FlowForge** [comment]
@ZJvandeWeg I opened a PR adding the form field and linked it to all these issues, they'll be all closed when the PR is merged.
