### ISSUE TITLE
Create PDF version of Opto 22 case study

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1426]
### Description

Create a PDF document of the case study so that it can be available to download via a form 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-FlowForge** [comment]
@Hasmin-AC this one is ready too.
It's in [here](https://drive.google.com/drive/folders/1QXCso0HQPbShrB5_8N0n_sDnIlluUaaI?usp=drive_link)

I can't find an issue requesting a pdf version of the PIDD story, but I'm assuming we'll need that one too, right?

**Comment by Yndira-FlowForge** [comment]
By the way, would we be interested in password-protecting these PDFs to restrict edit capabilities?
