### ISSUE TITLE
Webinar January 2024 with balena

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1435]
### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

**Inspirations:**
- <link here>
- <link here>
Image at the bottom of the file
https://docs.google.com/document/d/1DxiOsySUy4Y_oTfH2wFQ0ZSuWk8WSG2XkXmlsUsaCgQ/edit

**Comment by Yndira-FlowForge** [comment]
Hi @gdziuba I'm not sure I understand what you need here.
Is it two images? 
1. The regular one with the webinar info to add it to the web.
2. An additional diagram to showcase **during the webinar**. Or do you want to include that image in our web too? I'm asking to understand when do you need this image by...

**Comment by Yndira-FlowForge** [comment]
I know you didn't explicitly ask for this one, but I created it just in case this might speed things up regarding the announcement of the webinar.
![webinar-january-2024](https://github.com/FlowFuse/website/assets/129537638/43c796f5-a313-4483-8a5d-d615357719b7)

**Comment by Yndira-FlowForge** [comment]
> Image at the bottom of the file

Not sure what I'm supposed to do with this one. Recreate it with our colors? Replace balena's logo? Add FlowFuse logo somewhere?

**Comment by gdziuba** [comment]
Thanks @Yndira-FlowForge
