### ISSUE TITLE
Art for Blog: Send File to Node-RED

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1446]
### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

Blog Art

[Link to PR](https://github.com/FlowFuse/website/pull/1445)

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-FlowForge** [comment]
Hi @gdziuba I just added it to the PR 😉 

![Image](https://github.com/FlowFuse/website/assets/129537638/2f6afed9-1848-4fc7-b488-2ce8f6edfa60)
