### ISSUE TITLE
Solution page for agriculture

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/website#1450]
### Description

With the PIDD case study published, and opportunities in agriculture in the pipeline I expect there's more users that are looking for a solution page on agriculture.

/cc @Hasmin-AC 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Hasmin-AC** [comment]
Working Content doc  - https://docs.google.com/document/d/1MUMZr9Pk6gCMNeWCca0Zcm_0Ttmy94c3q2JYkXXjfk8/edit

**Comment by ZJvandeWeg** [comment]
Happy to make the initial PR @Hasmin-AC when it's ready!

**Comment by ZJvandeWeg** [comment]
Duplicate of: https://github.com/FlowFuse/customer/issues/139
