### ISSUE TITLE
Art - SOC2 Blog Announcement

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1466]
### Description

**Considerations:**

This is for the [Blog ](https://github.com/FlowFuse/website/pull/1465 ) art for SOC 2 compliance announcement.

[Advantage Partners](https://advantage-partners.com/)

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-FlowForge** [comment]
Hi @gdziuba can you elaborate a bit more on this? Why is the Advantage Partners link in the description? Should I add their logo?

Did we gain some kind of SOC 2 badge? I looked for one on Google but found different designs and I'm not sure which one is the official.

**Comment by gdziuba** [comment]
@Yndira-FlowForge 

Advantage is the partner we went through. I don't think it is necessary to use their logo.  I linked them for the description of what SOC 2 was for inspiration. 

We received SOC 2 compliance at the end of last year, and this is a blog announcement of that accomplishment.  This is necessary for many customers to leverage FlowFuse.  They look for this certification.

**Comment by Yndira-FlowForge** [comment]
Hi @gdziuba I just added it to the PR


![Image](https://github.com/FlowFuse/website/assets/129537638/fe0afc84-1b12-4ca2-8860-9b241451c5f3)
