### ISSUE TITLE
Blog Art - Import a File into Node-RED with Dashboard 2.0

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1467]
### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

This Blog is in alignment with Send a File to Node-RED.  Except it is importing leveraging Dashboard 2.0.

[Dashboard 2.0 ](https://github.com/FlowFuse/website/blob/a4969ac46f168abd5e3f509caef92fc0ac853469/src/blog/2024/01/images/csv-dashboard.png)

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-FlowForge** [comment]
Does it mean it's imported through the dashboard? Like a UI for attaching a file?

**Comment by gdziuba** [comment]
@Yndira-FlowForge Yes. It does.

**Comment by Yndira-FlowForge** [comment]
@gdziuba here's a quick version

![Image](https://github.com/FlowFuse/website/assets/129537638/c7e509f0-7c59-4af6-a007-949ca4143b2d)
