### ISSUE TITLE
Improvements to explore resources section on Home page 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1509]
### Description

 - Add sub title "Latest on the blog" to first column and list titles only of latest 3 blogs. 
 - Add title "Webinar" more prominently for middle column and list title, date and "Register now" CTA.  

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-FlowForge** [comment]
Hi @Hasmin-AC  It would be like this

<img width="1439" alt="Screenshot 2024-01-15 at 13 15 47" src="https://github.com/FlowFuse/website/assets/129537638/c36e8458-2552-4448-97c5-4e523f7ab017">

**Comment by Hasmin-AC** [comment]
Apart from increasing the sub header titles if possible, this looks good to go from me. Thanks!
