### ISSUE TITLE
Capture data from the edge social tile

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/website#1521]
### Description

**Considerations:**

It's a "Getting started" style post, after people have gone through their first flow. Would be great if the style could be alike: https://github.com/FlowFuse/website/issues/1511

**Inspirations:**
- Edge location, not in FF Cloud
- The agent enables management of the Node-RED instance elsewhere. Maybe show an editor or so on an edge, connected to FlowFuse cloud?

PR: https://github.com/FlowFuse/website/pull/1520

**Comment by Yndira-FlowForge** [comment]
I've added it to the PR


![Image](https://github.com/FlowFuse/website/assets/129537638/58113a73-1bbb-4c58-b406-91d362f266bc)
