### ISSUE TITLE
Blog post: Node-RED Keyboard Short Cuts

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1524]
### Description

MousePad giveaway?

**Comment by ZJvandeWeg** [comment]
Feels weird we're not giving away a keyboard in that case?

**Comment by Hasmin-AC** [comment]
create as a short blog for SEO and and not as swag.

**Comment by ZJvandeWeg** [comment]
Agreed @Hasmin-AC @sumitshinde-84. Would be a great one at `/node-red/shortcuts`
