### ISSUE TITLE
Blog post image 2.0 release

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/website#1527]
### Related Issue

https://github.com/FlowFuse/website/pull/1526

### Description

**Considerations:**
- Blog post image for the 2.0 Release

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-FlowForge** [comment]
Hi @MarianRaphael I just added it to the PR


![Image](https://github.com/FlowFuse/website/assets/129537638/66e136c5-87c0-4617-8858-e24a30ceded6)
