### ISSUE TITLE
Tile: Dashboard 2.0 GA Announcement

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/website#1542]
### Related Issue

https://github.com/FlowFuse/website/issues/1489

### Description

**Considerations:**
- For attaching to a Blog Article

**Inspirations:**
- Not too sure here, open to ideas - emphasis on the title. Doesn't have to be anything too fancy.

**Comment by Yndira-FlowForge** [comment]
Hi @joepavitt 

![Image](https://github.com/FlowFuse/website/assets/129537638/3d30569d-a211-4535-8bec-bb4b1b4c5734)

**Comment by joepavitt** [comment]
Can we go "Node-RED Dashboard 2.0" on the title please?

**Comment by Yndira-FlowForge** [comment]
Sure!


![Image](https://github.com/FlowFuse/website/assets/129537638/843385a9-e9b7-452b-9ed9-d5da3a93c705)
