### ISSUE TITLE
Tile: Multi User Dashboards

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/website#1543]
### Related Issue

https://github.com/FlowFuse/website/issues/1489

### Description

**Considerations:**
- Blog Article Tile

**Inspirations:**
- Thinking three displays with pseudo-dashboards on them (each slightly different), user icon/profile sat in front of each screen

**Comment by Yndira-FlowForge** [comment]
Hi @joepavitt did you mean something like this?


![Image](https://github.com/FlowFuse/website/assets/129537638/5ba02711-6961-4c40-8714-b3328fdc7470)

**Comment by joepavitt** [comment]
Perfect!
