### ISSUE TITLE
Create landing page for "Free consultation"  

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1617]
### Description

New campaign on providing expert advice to attract new MQLs. This will be the landing page for  leads to schedule a free consultation. It will be linked from an email to start with. 

Here is the [Content for landing page ](https://docs.google.com/document/d/183IPxXzU-zuoDjDutJKMImx9mIfdgHV7kXuGw7g3WUs/edit)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-FlowForge** [comment]
Hi @Hasmin-AC,

For the initial iteration, we can use the /book-demo template. We have the option to switch to a two-column layout later if you prefer, but considering the short length of the content, a single column layout might be more suitable.

**Comment by Yndira-FlowForge** [comment]
@Hasmin-AC Is something like this what you had in mind?

![Image](https://github.com/FlowFuse/website/assets/129537638/99fec70c-a0e5-476f-a82e-d933958a8ab6)

**Comment by Hasmin-AC** [comment]
Yes this works. Couple of notes:
1. Can we make the title be all in one line? 
2. Make the "Our expertise...." title bigger. 

Also note that its a form that placed on the right hand side and not a calendar. The form ID is on the doc.

**Comment by Yndira-FlowForge** [comment]
Ok, this is just a Figma File, I can't check the form until I add it to the frontmatter (or maybe there's a way of tracking it in hubspot using the ID?). It'll render whatever is linked to that form ID.

**Comment by Yndira-FlowForge** [comment]
> I can't check the form until I add it to the frontmatter (or maybe there's a way of tracking it in hubspot using the ID?)

Found it on HS!!
