### ISSUE TITLE
Blog Art for Connecting Node-RED to an OPC server

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1626]
### Description

Title: Connecting Node-RED to a Kepware OPC server.

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-FlowForge** [comment]
Hi @gdziuba here it is 😃 

![Image](https://github.com/FlowFuse/website/assets/129537638/3f28ba47-c4cb-44af-93ae-0ab77c815597)
