### ISSUE TITLE
Blog art for 'Bringing Software Development practices to Node-RED'

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/website#1632]
Blog post: https://github.com/FlowFuse/website/pull/1635

### Description

Writing a blog post for this week around how common software development practices can be applied to Node-RED - specifically linting, debugging and testing.

**Comment by knolleary** [comment]
Added link to the draft blog post for more context.

**Comment by Yndira-FlowForge** [comment]
Hi @knolleary I just added it to the PR

![Image](https://github.com/FlowFuse/website/assets/129537638/ad119840-12bd-4684-a0e4-b60ef5a055ca)
