### ISSUE TITLE
Update templates and colour scheme

### ISSUE THREAD

**Issue by Yndira-FlowForge** [FlowFuse/website#1655]
We're keeping the shades of grey and Indigo, making the latter the main color.
We'll change the red hue to a more orange one to better align with the brand's attributes, and we'll only use it as an accent color.

<img width="354" alt="Screenshot 2024-02-12 at 17 39 18" src="https://github.com/FlowFuse/website/assets/129537638/20a34390-f41f-4bd2-bd1a-950c6ac62c23">

This is the proportion of colors we'll use:
<img width="871" alt="Screenshot 2024-02-12 at 17 44 16" src="https://github.com/FlowFuse/website/assets/129537638/5fde7d7d-893d-4bd2-ab98-e23480ae9883">

The handbook is going to be updated accordingly.

**Comment by ZJvandeWeg** [comment]
Looks great!
