### ISSUE TITLE
Indicate true pricing on the website

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/website#1662]
### Description

FlowFuse offers pricing with discounts, which are not published on the website. The pricing however is based on a formula, and can be shown to the end-user.

The idea is to show the price per instance for the prospect, so they have a better indication of what to expect.

### Epic/Story

https://github.com/FlowFuse/website/issues/1661

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
@Yndira-FlowForge If you go monthly, there's currently no automated way we provide discounts on cloud. So maybe remove the sliders when monthly is selected?

**Comment by Yndira-FlowForge** [comment]
But there's no way to add a discount because it's a fixed amount of instances/devices/members, so the only possible discount would be if they could pay the whole year in advance, right?

Maybe we could make the monthly the default one, with the three options, and annually remove the starter option? or leave it with a 'contact us' button instead of 'try for free'?

**Comment by Yndira-FlowForge** [comment]
Which option?
1. Remove the starter option in 'annually'
2. Keep it with a 'contact us' button instead of 'try for free' and a fixed price if the whole year is paid in advance.

(I like the second one the better)

**Comment by ZJvandeWeg** [comment]
The starter tier is too cheap for us to talk to them. Remove it instead

**Comment by Yndira-FlowForge** [comment]
@ZJvandeWeg according to you message

> let’s provide more clarity. Ideally only for self hosted...

We can maintain the toggle as it currently stands, offering options for cloud and self-hosted. Within the self-hosted version, we can incorporate a slider and radio buttons to display annual or monthly prices, like this:



![Image](https://github.com/FlowFuse/website/assets/129537638/f413c56a-4d1e-45ec-b3fa-5bc65b9bcb4c)



![Image](https://github.com/FlowFuse/website/assets/129537638/c38a898c-b330-486a-9bb6-6a4e5a749f83)

**Comment by Yndira-FlowForge** [comment]
A/B tests seem to be working again, we could run an experiment with one of these options vs. our current pricing page and see how it goes. WDYT?

**Comment by Yndira-FlowForge** [comment]
A/B tests seem to be working again, we could test one of these options vs. our current pricing page.
