### ISSUE TITLE
Diagram for the Power Workplace customer story

### ISSUE THREAD

**Issue by robmarcer** [FlowFuse/website#1678]
### Related Issue

https://github.com/FlowFuse/website/issues/1677

### Description

I want a graphic to go with this customer story. The image should show a NR cloud instance communicating to the NR instance running on PLCs which are monitoring and managing equipment in an office building such as HVAC, lighting, presence detectors, power usage, air quality sensors. 

https://www.powerworkplace.com/

**Comment by Yndira-FlowForge** [comment]
Hi @robmarcer here it is:

![Image](https://github.com/FlowFuse/website/assets/129537638/e7bcb99b-c5fc-4e00-8832-e8d586ce6c1c)

I'll upload it to the PR as an SVG. There are so many details that don't look as good in a PNG file.
