### ISSUE TITLE
Blog: Citizen Development

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1684]
### Related Issue

1683

### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

I don't have a date just yet, but Monday at the latest.  I might write another blog for Monday.  

Title: Citizen Development: Unleashing Domain Experts

Non-stereotypical programmer in front of a computer programming in low code.

Hands of Guy in suit programming in node red.

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-FlowForge** [comment]
Hi @gdziuba here it is


![Image](https://github.com/FlowFuse/website/assets/129537638/14df054d-974d-4715-bf29-c179f23a7f30)
