### ISSUE TITLE
Blog: Marian 24/03/13

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1701]

**Comment by gdziuba** [comment]
Hey @MarianRaphael, do you have a topic for this blog?

**Comment by MarianRaphael** [comment]
Yes, an updated FlowFuse Architecture including the Use Case description about: Project Nodes & Device Agent use case

**Comment by gdziuba** [comment]
@MarianRaphael Thanks for the update.  Sounds good.
