### ISSUE TITLE
Updating url and title of Blog - Storing Data: Getting Started with Node-RED

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1720]
### Description

As per our discussion will be great to update this [blog's ](https://flowfuse.com/blog/2024/02/taking-it-further-with-node-red/) title, and url to "Structuring messages in Node-Red" 
There also might be some body text updates to be more inline with this new title along with the sub header that's specific to the topic. 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
@Hasmin-AC I don't think the title  reflects the request. Can you update it?
