### ISSUE TITLE
Updating Manufacturing solutions page

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1721]
### Description

Can you please add a resources section to the bottom of the page along with the CTAs to try/install FlowFuse? 
We can list the following:
https://flowfuse.com/customer-stories/leveraging-node-red-and-flowfuse-to-automate-precision-manufacturing/
https://flowfuse.com/customer-stories/stfi-future-of-textile-powered-by-node-red/
https://flowfuse.com/customer-stories/manufacturing-digital-transformation/
https://flowfuse.com/blog/2023/10/citizen-development/

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-FlowForge** [comment]
Hi @Hasmin-AC check out this mock up, I this what you had in mind? (The articles are not the ones on the list, I took them from another page to demonstrate the layout).



![Image](https://github.com/FlowFuse/website/assets/129537638/a99d67f6-e49d-4e0c-b33c-5f9a553d720f)

**Comment by Hasmin-AC** [comment]
Yes this can work, but can we add short descriptions to the resource boxes? 
Also lets take off the sub header in the deployment section. For the CTA's there, Cloud should be "Sign up", and Self managed should go to "Install". 
Thanks!

**Comment by Yndira-FlowForge** [comment]
can we add short descriptions to the resource boxes

We can, for the blog post I can take the description from the front matter, but the customer stories don't have descriptions, could you please provide them? A really short text would be the best.

This is how it currently looks, only with the titles and I think it already looks kind of crowded (I haven't updated the images)


![Image](https://github.com/FlowFuse/website/assets/129537638/f10513eb-c4ee-43a6-9a49-671d48763d3d)

**Comment by Hasmin-AC** [comment]
Would the Images have the title of the content? If thats the case i can provide a description (let me know character limit) and we have only description as text and the title in image.

**Comment by Yndira-FlowForge** [comment]
> Would the Images have the title of the content?

Only the blog post has the image with title, the customer stories are photos or graphics with no text.

**Comment by Hasmin-AC** [comment]
OK. Then for the case studies, we'll stick to title only but precede with "Case Study: <title>" 

For blog since the title will be on the image, lets add the short description as text.
