### ISSUE TITLE
Implement flowviewer

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/website#1723]
### Description

https://github.com/node-red/flow-library/pull/99/files 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-FlowForge** [comment]
@ZJvandeWeg 
I asked @joepavitt to point me in some direction to get started with this, because honestly, I wasn't sure where to start. 
He said copy+pasting could be messy, specially with eleventy and opened this issue: https://github.com/FlowFuse/node-red/issues/8
