### ISSUE TITLE
Blog Art: "Run FlowFuse on Siemens IoT2050"

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1737]
### Related Issue

#1495

### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

Title: "Run FlowFuse on Siemens IoT2050"

[IoT2050](https://iot2050.com/)

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-FlowForge** [comment]
Hi @gdziuba here it is

![Image](https://github.com/FlowFuse/website/assets/129537638/09f4344b-900a-4b32-a537-17ca191bcc8b)
