### ISSUE TITLE
Blog: "Why Low-Code is better"

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1746]
### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

**Inspirations:**
- <link here>
- <link here>

picture of Node-RED / FF  (Greater Than > ) High Code (python or java)

Node-RED > obscure structured text

**Comment by Yndira-FlowForge** [comment]
Hi @gdziuba is there a PR or a branch for this article?

**Comment by Yndira-FlowForge** [comment]
Hi @gdziuba here it is. I tried with the `>` symbol, but it looked more like it was pointing to the code... 

![Image](https://github.com/FlowFuse/website/assets/129537638/d388bcc9-ab37-40c8-b819-ccf64db7cbad)
