### ISSUE TITLE
Art Request: March Webinar

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1747]
### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

![image](https://github.com/FlowFuse/website/assets/8887166/ce1702c6-7581-4afe-bb86-6febe5808e18)

Webinar is with Kudzai Manditereza

Title is: Building Unified Namespace using Node-RED and MQTT

**Inspirations:**
- <link here>
- <link here>

**Comment by joepavitt** [comment]
Just to check @gdziuba - you just need the webinar tile here? This task is just constrained to the Art Request?

**Comment by Yndira-FlowForge** [comment]
I'll do it @gdziuba.  
Can you please confirm the date?
Do you need it by today? Or is tomorrow ok?

**Comment by gdziuba** [comment]
The date is March 26th and the usual time.  Tomorrow is Fine, unless @Hasmin-AC has an objection.

**Comment by Hasmin-AC** [comment]
Tomorrow should be fine.

**Comment by Yndira-FlowForge** [comment]
Here it is @gdziuba 
I already added it to your branch

![Image](https://github.com/FlowFuse/website/assets/129537638/54436581-0d85-466b-993d-32fff836b3ac)

**Comment by gdziuba** [comment]
@Yndira-FlowForge can you add my picture as well. It will be a joint webinar?

**Comment by gdziuba** [comment]
@Yndira-FlowForge Can we adjust so this says Tuesday, not Thursday?  I should have specified that.

**Comment by Yndira-FlowForge** [comment]
Hi @gdziuba I'm on it.
Would it be possible to include all the necessary information for each tile in the issue description when opening it? 

- Title
- Date/time
- Name of hosts
- Title/job description of each host

**Comment by Yndira-FlowForge** [comment]
Here's the [PR](https://github.com/FlowFuse/website/pull/1769)
