### ISSUE TITLE
Update social media profiles

### ISSUE THREAD

**Issue by Yndira-FlowForge** [FlowFuse/website#1750]
We need to update the social media profile images with the ones in this folder: https://drive.google.com/open?id=1eWANC3ilDwgtGWS2GEU4jMKWXr_uEeqs&usp=drive_fs

We're using a new red hue, so even the icon has to be updated, I added the file "FF-con_light_bg.png" in that folder that you can use for the profile image.

I can update:
- [x] Facebook
- [x] Twitter
- [x] Youtube

@ZJvandeWeg 
- [x] GitHub
- [x] LinkedIn

@gdziuba 
- [x] Discord
- [x] Twitch

**Comment by gdziuba** [comment]
Done.

**Comment by Yndira-FlowForge** [comment]
@gdziuba 

> We're using a new red hue, so even the icon has to be updated, I added the file "FF-con_light_bg.png" in that folder that you can use for the profile image.
