### ISSUE TITLE
Missing information in blog "Capture Data from edge devices with Node-RED"

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1751]
### Description

In the section "Install the FlowFuse agent through Docker" there seems to be content missing. 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
Can you link the page?

**Comment by Hasmin-AC** [comment]
https://flowfuse.com/blog/2024/01/capture-data-edge-with-node-red-flowfuse/

There's some content missing in the "Install the FlowFuse agent with npm" section too.
