### ISSUE TITLE
Content: Instance Protection Mode

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/website#1756]
## Original Issue
https://github.com/FlowFuse/flowfuse/issues/3488

## Description

In our ongoing commitment to provide a secure and controlled environment for our FlowFuse users, particularly for Team Owners overseeing production instances, we recognize the importance of stringent access controls. The new Protected Mode feature is designed to safeguard production environments, ensuring that any modifications are made with the utmost caution and only by authorized personnel.

**Key Points to Cover**

- Explain the concept of Protected Mode and its significance in safeguarding production instances against unauthorized changes.
Emphasize the ease of activation through a simple toggle within Instance Settings.
Editor Restrictions Under Protected Mode:

- Detail the viewer-only access for Team Members and Viewers, underscoring that only Owners can make modifications.
Highlight the importance of this restriction in preventing unintended alterations to critical environments.
DevOps Pipeline Execution Control:

- Clarify that only Owners have the authority to initiate and execute pipelines targeting a protected instance.
Stress the role of this control in maintaining the integrity of production environments by ensuring that any changes undergo proper supervision.

## Demo

https://flowforgeworkspace.slack.com/archives/C04GW82DJFK/p1709037813497819

## Expected Live date

March 14th

**Comment by gdziuba** [comment]
IMO, this seems like a redundant issue.  The content above can be put in a comment on the original issue.  Then we should link the comment in the content strategy meeting doc. The content is great. We need more interlock between the customer teams and engineering.

**Comment by gdziuba** [comment]
Prevent Mission critical instances changes.  Extra layer of security.

**Comment by gdziuba** [comment]
@MarianRaphael @Hasmin-AC 

https://github.com/FlowFuse/website/assets/8887166/4fe35b22-66c9-4042-b0ed-aa9a210c1fe8
