### ISSUE TITLE
Hubspot emails header banner with updated branding 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1765]
### Description

Width: 204 px 

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-FlowForge** [comment]
Hi @Hasmin-AC I updated the [newsletter template](https://app-eu1.hubspot.com/content/26586079/create/email/all?subcategory=drag_drop_email&emailType=REGULAR) 

![Image](https://github.com/FlowFuse/website/assets/129537638/87e3f834-c432-48ec-841c-7aeb3d5ef8b7)

And the saved sections that appear at the bottom left of the newsletter editor:


![Image](https://github.com/FlowFuse/website/assets/129537638/6ff1db2e-dc6a-4999-b504-cf53fb35c095)

**Comment by ZJvandeWeg** [comment]
@Yndira-FlowForge Should the issue be closed if it's "Done" in the project board?

**Comment by Yndira-E** [comment]
Hi @Hasmin-ACHi @Hasmin-AC, I noticed that the April newsletter was sent with the old template. Seems like it went out even without the logo... 
![image](https://github.com/FlowFuse/website/assets/129537638/479bd51b-dee3-4319-bfd2-9e9c425d2c93)
Could you please ensure that the next one goes out with the updated branding? In [this comment](https://github.com/FlowFuse/website/issues/1765#issuecomment-1988200584) I've described how to use the updated template.
