### ISSUE TITLE
Landing page for EBook

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1766]
### Description

Content with layout ideas are in [this doc](https://docs.google.com/document/d/10VTTtcxja4IT76QZ4DQzGU2ludyuhlBASTS7GRAba50/edit?usp=sharing) but open to better layout option for eBooks. 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC I updated the style of the first few pages of the ebook, so you have a guide to update the rest of the pages.

Regarding the ebook page, how about this?


![Image](https://github.com/FlowFuse/website/assets/129537638/b5c499f3-a9ff-418f-a779-4aac440a66a8)

**Comment by Hasmin-AC** [comment]
Looks great Yndira! will let you know when the PDF is updated for us to go live.
