### ISSUE TITLE
New Google Docs Template for Case studies/eBooks with new branding 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1770]
### Description

Replacing the current black with indigo. 

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-FlowForge** [comment]
Hi @Hasmin-AC I already had an [issue](https://github.com/FlowFuse/website/issues/1752) opened for this, so I'm closing this one 😉
