### ISSUE TITLE
Docs Outline to include Certified Node, plus notable ones

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1777]
### Description

- Core-Nodes
  - Common
  - Function
  - Network
  - Parsers
  - Sequence
  - Storage
- Non Core-Node
  - Certified-Nodes
    - Should These be Organized Similarly?
  - Common (Vote to be Certified?)
    - e.g. Barcode Scanner

Commonly used nodes—These are Nodes we have found that are often invaluable to many organizations. We wanted to acknowledge them here and give a guide on how to use them. At this point, these nodes haven't gone through the analysis for certification. They may never be certified, but we find it essential to add additional details.

## To-Do

- [ ] Outline a structure for each node and information that should be included for each
  - [ ] Similar Nodes eg

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by gdziuba** [comment]
@Yndira-E and @ZJvandeWeg,  This was the results from the discussion from the [Content Strategy](https://docs.google.com/document/d/13xDEQP5d4pJWhlpHZ1HRcJVAQdS_cd4ocL0swwD4WaU/edit#heading=h.chqyuxeanx3a) discussion.  The goal of this would be to create an area for Certified Node, then a place for additional Nodes that may or may not make the cut for certified node, but are worth the acknowledgment.

**Comment by Yndira-E** [comment]
Reviewing the discussion and the description, I'm thinking a new section in the `/core-nodes` page for non core-nodes isn't the right approach.

If I'm understanding correctly, the idea would be to take advantage of the SEO performance of the core-nodes content to expose our certified nodes. Maybe just by changing the page to be something more "generic", we could add core-nodes, certified-nodes, and all the packages we see fit in a more sensible way.

And we'd need some structure for each certified node content. @gdziuba will you take care of the creation of that content?

It could be something like:

**Description**
- What does it do
- When does it do it
- Which nodes are part of the package

**How to use it**
- Examples

**Why is this core-node relevant/important**

WDYT?

**Comment by gdziuba** [comment]
@Yndira-E,   I like this approach.

So if I am thinking we will go from:

```/core-nodes```
to:
```/nodes/core-nodes```
and 
```/nodes/certifed-node```
and it will make room for
```/node/community-nodes```
In the future.

Each Node should include the following content (using [split ](https://flowfuse.com/node-red/core-nodes/split/#what's-the-split-node-in-node-red-used-for%3F)as an example):

- Purpose
- Examples
- Node Documentation
  - Inputs
  - Outputs
- References (Optional)
  - Similar Nodes
  - Reference Blogs

**Comment by ZJvandeWeg** [comment]
In the path of the URL it should be packages I think, not nodes. Also, per REST it should be plural. 😀

**Comment by gdziuba** [comment]
Works for me.

**Comment by gdziuba** [comment]
Another thing to consider is that some *packages* will have multiple nodes.  How do we want to handle that?  For example, the influxdb node has 3 nodes in it.  Do we want a separate page for each one?  So it would be something like this:

```/packages/certified-node/influxdb/influxdb-out```
```/packages/certified-node/influxdb/influxdb-batch```
```/packages/certified-node/influxdb/influxdb in```

**Comment by Yndira-E** [comment]
@ZJvandeWeg If I understood correctly, you're working on this, right?

**Comment by ZJvandeWeg** [comment]
@Yndira-E I've done some work on the core nodes to prepare, but I feel like the `/node-red` page should behave like `/node-red/core-nodes/`. To have a sidebar so we can build pages on them.

**Comment by Yndira-E** [comment]
I'm guessing that idea is linked to [this comment](https://github.com/FlowFuse/website/pull/1963#issuecomment-2071766785), right?

We have [this issue](https://github.com/FlowFuse/website/issues/1961) for the Node-RED page iteration. I'll add your comments there, and we can continue the conversation in that issue.

**Comment by gdziuba** [comment]
@ZJvandeWeg or @Yndira-E, Where can I find the PR so that I can work on the certified nodes' documentation?  ZJ, I think you had created something while in Hannover.

**Comment by gdziuba** [comment]
[Slack thread that discusses thoughts on certified nodes.](https://flowforgeworkspace.slack.com/archives/C02TG4WH5PC/p1719928245031949)
