### ISSUE TITLE
Updating webinar page template to include two presenters 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1801]
### Description

Can we update the title "Hosted by" on the right hand side to "Presented by" and include the additional presenter bios when there's more than one presenter? 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC this is already possible, check out https://flowfuse.com/ask-me-anything/ama-nodered-may/

However, I realize the handbook doesn't mention how to add more than one host or blog author, nor does it explain how to add someone from outside of FlowFuse. I'll update it accordingly.

**Comment by Yndira-E** [comment]
@Hasmin-AC [here's](https://github.com/FlowFuse/website/pull/1806) the update in case you want to check it out. I guess this could be useful to @gdziuba too 😃

**Comment by Hasmin-AC** [comment]
Thanks for updating handbook, But can we also change the text "Hosted by" to "Presented by" in the template.
