### ISSUE TITLE
Image Template for new Feature Promotion

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1808]
### Description

I would like a template that can be easily updated to create a tile for blogs focused on feature updates.  

To be included in the blog are the following:

- Title
- FlowFuse Logo
- Words including "New Feature"

I like this tile here for inspiration:
https://flowfuse.com/blog/2024/03/installing-operating-node-red-behind-firewall/

**Comment by Yndira-E** [comment]
Hi @gdziuba I just added it to our [template gallery](https://docs.google.com/presentation/u/0/?ftv=1&folder=0AK4B4zrgZMaqUk9PVA&tgif=d). It's the one called Blog Tile - FlowFuse New Feature
