### ISSUE TITLE
Blog tile: Scaling Node-RED with FlowFuse: Differences between a FlowFuse Instance and a Device Instance

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1818]
### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

**Inspirations:**
- <link here>
- <link here>

Title: "Scaling Node-RED with FlowFuse: Differences between a FlowFuse Instance and a Device Instance"

Thoughts are to include the Architecture diagram of FlowFuse with Device Agents.  

https://github.com/FlowFuse/website/pull/1817

**Comment by Yndira-E** [comment]
Hi @gdziuba I've just pushed it to the PR


![Image](https://github.com/FlowFuse/website/assets/129537638/f53044d5-30e4-43d7-be56-57e0e3b5a8a8)
