### ISSUE TITLE
Purdue Model in FlowFuse Style 

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/website#1823]
### Related Issue

https://github.com/FlowFuse/website/pull/1822

### Description

**Considerations:**
There is the Visualization from the ISA 99 standard. It would be great to have more or less the same visualization in a FlowFuse branded style.

**Inspirations:**
<img width="805" alt="purdue-model" src="https://github.com/FlowFuse/website/assets/73583313/6e58655c-f62e-4a6b-a05c-4683310e96dd">

**Comment by Yndira-E** [comment]
Hi @MarianRaphael, when do you need this by? Is the article ready and just waiting for the images?

**Comment by MarianRaphael** [comment]
No time pressure from my end. Article is good to go

**Comment by Yndira-E** [comment]
Hi @MarianRaphael here it is, I just added it to the PR




![Image](https://github.com/FlowFuse/website/assets/129537638/1e9c9411-f0e0-4ddc-9649-b7c79c7eb8b7)

**Comment by MarianRaphael** [comment]
Looks great!
