### ISSUE TITLE
Update Hello Bar and Resources footer in the homepage

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1839]
### Description

Now that the March webinar is done and we don't have an upcoming one schedule yet, lets update the Hello Bar on top to promote the eBook instead. The same should be done for the Resources section at the bottom.
Please use the following text for this:

Download the Ultimate Beginner Guide to a Professional Node-RED - Free eBook!

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC, for the banner, here are the instructions on how to change it. I'm sure you can handle that part: [Events Banner Instructions](https://flowfuse.com/handbook/customer/marketing/website/#events-banner)

Regarding the resources section, it was set up to automatically add the latest webinars. If there's an upcoming one, it displays that. If not, it shows the latest one, but not ebooks...

If you believe including this ebook is essential, I can make a temporary change to replace it. However, if this will be a recurring change, maybe it can't be automated anymore, and we'll have to manually update it each time.
