### ISSUE TITLE
Add Logo to Partnership page

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1849]
Attached is the GIS logo to be added to the [partnership page](https://flowfuse.com/partners/) under a new section "Strategic Partners" 
In an effort for the website to be less text heavy, we can remove the descriptions in each of the sections, as they are self explanatory. 

![Gallarus_logo_black_big](https://github.com/FlowFuse/website/assets/153527883/2c26b835-3602-4041-8f4c-55d40b36ae8c)

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC, to remove the text I would have to change the layout, we don't have enough logos to maintain the one we currently have. So, for the sake of iterations, I'm just adding the new section and we'll handle layout changes in a different PR.
