### ISSUE TITLE
Blog Art: Role Base Access Blog

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1854]
### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

Blog Post
Title: "Role-Based Access for your Node-RED applications"

Reference content:
Role-Based Access for your Node-RED applications

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-E** [comment]
Hi @gdziuba I just pushed it to the PR


![Image](https://github.com/FlowFuse/website/assets/129537638/b622a489-bc1f-4155-95b1-ad1a62a2a6ce)

**Comment by gdziuba** [comment]
@Yndira-E Thank you.
