### ISSUE TITLE
April 2024 Webinar 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1888]
### Related Issue

#1885

### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

Title: Elevating Node-RED: A FlowFuse Platform Update
Date/time: Tuesday April 30, 17:00 CET (11:00 ET)
Name of hosts: Nick O’Leary
Title/job description of each host: Co-founder & CTO, FlowFuse

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC here it is


![Image](https://github.com/FlowFuse/website/assets/129537638/807d218b-d028-4d18-b243-7efc2412c4b1)
