### ISSUE TITLE
FlowFuse Dedicated Image

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/website#1891]
### Related Issue

https://github.com/FlowFuse/website/pull/1890

### Description

**Considerations:**
- Image for the blog post about the Introduction of FlowFuse Dedicated

**Comment by Yndira-E** [comment]
Hi @MarianRaphael I've just pushed it to the PR:


![Image](https://github.com/FlowFuse/website/assets/129537638/db2d63f2-f9b3-4122-a846-91154d71c8f7)
