### ISSUE TITLE
Robustel Blog Art Request

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1899]
### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

**Inspirations:**
- <link here>
- <link here>

Can we make a blog similar to the IoT 2050 artwork for [robustel eg5120](https://www.robustel.com/download/8339/?tmstv=1712329311).

[Site Documentation](https://www.robustel.com/product/eg5120-industrial-edge-computing-gateway/)

- [ ] Title

**Comment by Yndira-E** [comment]
You mean this one, right?


![Image](https://github.com/FlowFuse/website/assets/129537638/2060edb9-5371-4a60-a66e-4e586e8b6c0f)

What would be the title?
"Run FlowFuse on Robustel EG5120"?

**Comment by gdziuba** [comment]
@Yndira-E Yes

**Comment by Yndira-E** [comment]
Does the Node-RED logo make sense here?

![Image](https://github.com/FlowFuse/website/assets/129537638/fa6a1b00-4ca5-4d94-ae98-69d33f513c80)

**Comment by ZJvandeWeg** [comment]
@gdziuba Can you reply to ^?

**Comment by ZJvandeWeg** [comment]
@gdziuba This item seems to be overdue about 10 days, can you post an update here?

**Comment by gdziuba** [comment]
Yes.  I prioritized another blog over this one.  I believe it was the hannover messe post.
