### ISSUE TITLE
Blog Art : Admin Dashboard with Node-RED Dashboard 2.0

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#1906]
### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

**Blog Post**
Title: "Building Admin Dashboard with Node-RED Dashboard 2.0"

**Reference content:**
- https://github.com/FlowFuse/website/pull/1883

**Comment by Yndira-E** [comment]
Hi @sumitshinde-84 I've just pushed it to the PR


![Image](https://github.com/FlowFuse/website/assets/129537638/bb3ac3c0-2df4-436b-89da-5beed7ca99f5)
