### ISSUE TITLE
Blog Art : MongoDB with Node-RED 

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#1912]
### Description

**Considerations:**
- Blog Tile : Using MongoDB with Node-RED
- Recreation of this image in our FlowFuse colors :  https://github.com/FlowFuse/website/blob/6a1300af77bef95934856ce7826ac15e20b846ec/src/blog/2024/04/images/using-mongodb-with-node-red-annotomy-of-mongodb-document.png

**Reference content:**
- https://github.com/FlowFuse/website/pull/1900

**Comment by Yndira-E** [comment]
Hi @sumitshinde-84 I've just pushed it to your branch


![Image](https://github.com/FlowFuse/website/assets/129537638/3c501d97-33da-49d1-9df5-3df48a3256f9)

**Comment by sumitshinde-84** [comment]
Hi @Yndira-E, nice graphic! However, we need two images: one for a blog tile and another to explain the MongoDB document structure. You've created the MongoDB anatomy image. Could you also create a blog tile? Sorry for the misunderstanding That was my mistake; I should've provided more description initially.

**Comment by Yndira-E** [comment]
Oh ok, I get it now. I did think it was kind of weird to have lines of code as part of the blog tile 😅

**Comment by Yndira-E** [comment]
Done!


![Image](https://github.com/FlowFuse/website/assets/129537638/bbaa2139-fb98-4873-82f9-a64529190650)
![Image](https://github.com/FlowFuse/website/assets/129537638/442d9afb-80a7-4cfc-9cdc-6f7546605545)
