### ISSUE TITLE
Blog Art : Using Webhooks with Node-RED

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#1918]
### Description

**Considerations:**
- Blog tile : Using webhooks with Node-RED

**Reference content:**
- https://github.com/FlowFuse/website/pull/1917

**Comment by sumitshinde-84** [comment]
@Yndira-E Yes, all the steps involve Node-RED. However, I need to update the blog and this diagram. So, for now, just creating a blog tile will be perfect. I will let you know when I update the diagram.

**Comment by Yndira-E** [comment]
I was planning on making this part of the blog tile. Do you have any suggestions for the tile artwork?

**Comment by Yndira-E** [comment]
@sumitshinde-84 ok, this would be the tile and let me know if you need me to work on the diagram when you've updated it

![Image](https://github.com/FlowFuse/website/assets/129537638/e3b9bac6-e3a7-409c-8a40-196b203287ad)

**Comment by sumitshinde-84** [comment]
@Yndira-E Nice graphics! I'll let you know when I update the diagram. After that, you can work on the diagram.
