### ISSUE TITLE
Thank you Page with meeting link embedded 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#1939]
### Description

Create thank you pages that have the book a meeting embedded that people will be taken to once they fill out a form. This can be applied to contact us and content downloads such as ebook, case study downloads etc. 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC you mean the book a demo form?
And, what other content would this page have? A "thank you" and the form?

**Comment by Hasmin-AC** [comment]
The meeting that should be embedded is the sales one: https://meetings-eu1.hubspot.com/flowfuse/sales and look similar to the Book a demo. 

Yes the top of the page will be Thank you for [the action they did]  and  for
 - Contact us follow up; the meeting link embedded with the title "Schedule a call now"
 - Content download follow up; sections for "Latest on our blog",  "See how Flowfuse can help with your next project. Book a call now" (meeting embed),  customers logos etc.

**Comment by Yndira-E** [comment]
@Hasmin-AC, this would be the content download follow-up thank you page as you described it.

![Image](https://github.com/FlowFuse/website/assets/129537638/15e1f2ea-f7e0-4157-be19-c3e61a830ba7)

However, I find it a bit odd to have the blog posts in the first section. Is it necessary to have them there? What do you think about swapping sections 1 and 2?

**Comment by Hasmin-AC** [comment]
How about placing them side by side so that they are both above the fold? For the blogs section, we can keep it simple and only show the titles (no image tile).

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC, ok, it will be like this:


![Image](https://github.com/FlowFuse/website/assets/129537638/8c8c9f93-9fe0-4a71-82f5-d14e24c77b08)
![Image](https://github.com/FlowFuse/website/assets/129537638/27fe7e90-4e0a-4d71-bd24-f93aef24e656)

**Comment by Hasmin-AC** [comment]
Yes, looks good.
