### ISSUE TITLE
Remove bg and other tweaks for the team entry

### ISSUE THREAD

**Issue by cstns** [FlowFuse/website#1947]
### Description

**Considerations:**
- Meet The Team website section

**Inspirations:**
https://flowfuse.com/team/

![profile](https://github.com/FlowFuse/website/assets/20094749/1610cf0c-544b-4443-9c80-02abbf84d485)

**Comment by Yndira-E** [comment]
Hi @sherbastian I've just pushed it to the PR 😉

**Comment by sherbastian** [comment]
Thank you!
