### ISSUE TITLE
Blog art: How to build an application with Node-RED Dashboard 2.0

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#1951]
### Related Issue
https://github.com/FlowFuse/customer/issues/157

### Description

**Considerations:**
- Blog tile : How to build an application with Node-RED Dashboard 2.0

**content reference:**
https://github.com/FlowFuse/website/pull/1950

**Comment by Yndira-E** [comment]
Hi @sumitshinde-84 I've just pushed it to the PR


![Image](https://github.com/FlowFuse/website/assets/129537638/5513acc4-9a0c-4642-804d-309a75eea73e)
