### ISSUE TITLE
Home page iteration

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/website#1960]
### Description

- [x] 1. Update description in the hero section
- [x] 2. In the second section, the "See how FlowFuse powers industries", replace the content with actual industries:
    - Manufacturing
    - Agriculture
    - Building management system
    - Logistics
- [x] 3. Replace benefits with values
- [x] 4. Replace get started > learn more with on premises (like in `/features`)

@Hasmin-AC I'll need the text for the points 1, 2 and 3. You can use the current length of the text we have in those sections as a guide, at least as a starting point to see how it looks.

### Epic/Story

#1932

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC, when do you think you could have the copy ready? I'm asking so I can set a target date that's realistic.

For the first iteration, perhaps we could include some descriptions for point two without linking them to the pages that haven't been created yet. We'll add the links when they're available.

**Comment by Hasmin-AC** [comment]
Started working on [the content](https://docs.google.com/document/d/1nu6jAqm6ePw-QB0G-SuZ43685vZEHOgiBKvUy8L5c2I/edit) . Need a day or two more to finish it

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC could you please tell me approximately when do you think it'll be ready? Just to set the target date for the issue. Thanks!

**Comment by Hasmin-AC** [comment]
Parts 1, 2 and 3 are done and can be found on the doc shared earlier. I would however want @ZJvandeWeg to confirm the Values section to make sure I've captured and summarized it accurately.

**Comment by Yndira-E** [comment]
Thanks @Hasmin-AC!

**Comment by Yndira-E** [comment]
@Hasmin-AC  This is how it looks with the suggested changes 

![Image](https://github.com/FlowFuse/website/assets/129537638/46603bf4-e181-480a-9edc-aa95c13c64c1)

I'm not sure if it's because I was used to the previous structure, but the paragraph before the pills that wasn't there before seems kind of out of places, at least visually, is it really necessary? 

And the short descriptions without the title makes it look unbalanced... Is it possible to make it longer? Like we discussed before, using the same text length each 'solution' currently has? 

Maybe taking that new description and somehow using it on each industry instead? Not exactly the same for the three of them, but inspired in that content?

**Comment by Hasmin-AC** [comment]
Yes we should keep the description as it provides an overview of how we are industry agnostic and not limited to certain industries only. It also gives us an opportunity to link to the Node-RED page as recommended by the SEO agency. 
How about spanning this description across the page to see how it looks? 

Maybe if the image height is smaller it will look more balanced? However if you insist i will try to come up with some additional titles that is not repetitive.

**Comment by Hasmin-AC** [comment]
note the main header should also remove the words "See how"

**Comment by Yndira-E** [comment]
Ok Hasmin, don't worry, I'll make it work with the copy you provided, thanks
