### ISSUE TITLE
Node-RED page iteration

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/website#1961]
### Description

1. The hero section will be more oriented to explaining what Node-RED is
2. The e-book will be the main CTA
3. If the content in the hero section makes the "What is Node-RED" content seem repetitive, we'll remove it
5. Add an anchor to FAQs, so we can share an URL that goes directly into that section

@Hasmin-AC I'll need the text for points 1 and 2. You can use the current length of the text we have in those sections as a guide, at least as a starting point to see how it looks.

### Epic/Story

#1932

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Hasmin-AC** [comment]
Requested SEO agency for input on this as well. Will share recommendations soon.

**Comment by Yndira-E** [comment]
I'm adding @ZJvandeWeg's comments from other issues related to this one so we can discuss:

https://github.com/FlowFuse/website/issues/1777#issuecomment-2074211914

> I feel like the /node-red page should behave like /node-red/core-nodes/. To have a sidebar so we can build pages on them.

https://github.com/FlowFuse/website/pull/1963#issuecomment-2071766785

> I start to believe we need to put this under /node-red/*. So this would be flowfuse.com/node-red/variables. We can move other blogs there too, to have one hub for all resources on how to leverage Node-RED with FlowFuse.

So, this would be like a documentation page, right? A completely different design than what we currently have, more educational and not commercial.

**Comment by Hasmin-AC** [comment]
Here's the [reworked content for the Node-RED page](https://docs.google.com/document/d/1YCgpSY_kWmjk_P2BGQi8dwd6uSo6USKB_tFU8u6jV7U/edit). 
One other recommendation from the SEO agency is to internally link to this page as much as possible from other pages and blogs.

**Comment by Hasmin-AC** [comment]
I will audit and categorize the blogs we have now to move them docs like the structure suggested by ZJ. URL can be Flowfuse.com/node-red/<category>/<topic> similar to core nodes

**Comment by Yndira-E** [comment]
This is how the landing page would look with the content provided by Hasmin.

@ZJvandeWeg This is what I meant when I said that what Hasmin described wasn't quite the usual documentation layout. However, it can work similarly to https://dashboard.flowfuse.com/, which has a landing page with a different structure from the rest of its pages. I believe you even suggested it in one of our meetings, and Hasmin mentioned it in the Google Docs attached to this issue.

@Hasmin-AC, the text in the hero section was a bit long. I tried to shorten it, but if you could make it even shorter, I think it would look better. Also, the deployment options, you mentioned dedicated in the doc, but now it has edge device instead. I kept it as we have it now, let me know if it will be replaced with the dedicated content.

Also, I was thinking that maybe we could add a secondary button, similar to the one on the homepage, that directs users to the learning resources pages. These pages would be the ones with left column where users can navigate through all the content we'll add there. You  both mentioned that this landing page should focus on educating people about Node-RED, so I believe that having a link to all the resources above the fold would be beneficial.

As part of an iteration, I could develop this landing page without the "SEE ALL" link or the secondary button mentioned above. And for the next one, we could build that centralized Node-RED resources page. What do you think?

![Image](https://github.com/FlowFuse/website/assets/129537638/81ab4d87-321b-4440-91e4-02f41dac0948)

**Comment by ZJvandeWeg** [comment]
Looks nice @Yndira-E !

**Comment by Hasmin-AC** [comment]
Looks Good @Yndira-E

How many words or characters would you like me to cut? One note about the existing page was that it was a little light on content so I wouldn't want to scale back too much. 

I will add some text for dedicated to add to the deployments section.

For the resources, the idea is to have something similar to https://flowfuse.com/node-red/core-nodes/, where it's like a documentation hub,  for things like Variables etc. We can go live with this for now and once I've curated the content we can implement and link for the next iteration.

**Comment by Yndira-E** [comment]
@Hasmin-AC 

> How many words or characters would you like me to cut?

Around 100, if possible

**Comment by Hasmin-AC** [comment]
See doc for revised intro text. 

Also lets add the question "Who uses Node-RED?" to the FAQ. Text for the answer to this is also in the doc.
