### ISSUE TITLE
Blog Art: Guide to Node-RED Variables

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#1964]
### Description

**Considerations:**
-  Blog tile : Beginner's Guide to Node-RED Variables

**Content reference**
https://github.com/FlowFuse/website/pull/1963

**Comment by Yndira-E** [comment]
Hi @sumitshinde-84 I've just pushed it to the PR.


![Image](https://github.com/FlowFuse/website/assets/129537638/341d17f5-0d5a-4cc9-a4a2-eb8cf04ca293)
