### ISSUE TITLE
May 2024 Webinar

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#1986]
### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

Title: Deploy FlowFuse on Industrial IIoT with NCD.io
Date/time: May 29th, 17:00 CET (11:00 ET)
Name of hosts: Grey Dziuba and Travis Elliott
Title/job description of each host: 
- Grey Dziuba - OT Data and Community Strategist
-  Travis Elliot - COO

**Inspirations:**
- <link here>
- <link here>

**Comment by gdziuba** [comment]
We have a meeting with NCD today and will be collecting the rest of the missing information plus a portrait of the cohost from NCD.  I created a ticket so we have it in the pipeline.  We want to get this completed before the Newsletter goes out.  Target for newsletter is Thursday.

**Comment by Yndira-E** [comment]
Hi @gdziuba I'll be ooo tomorrow. At what time will you send the newsletter?
Also, since you mentioned the newsletter, I'd like to take the opportunity to share [this](https://github.com/FlowFuse/website/issues/1765#issuecomment-2084833700) here too for visibility, regarding the template we should be using on HubSpot.

**Comment by gdziuba** [comment]
@Yndira-E Ah, gotcha.   @Hasmin-AC schedules it, but I help build out the content.  I have been copying from previous newsletters, I will pull this template today.

**Comment by gdziuba** [comment]
![1ol-dZWsSuj7PDiRdo8amYqc6_aCcv7BAJEcliTW8](https://github.com/FlowFuse/website/assets/8887166/056434b7-69e5-470c-bea2-99db1fbe570c)

**Comment by Yndira-E** [comment]
👋  here it is
![webinar-2024-may](https://github.com/FlowFuse/website/assets/129537638/4e6c5bbf-9bf6-4e63-a93e-f27f8e11240c)
