### ISSUE TITLE
Add co-presenter to May webinar page.

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#2009]
### Description

Need a headshot image of Travis Elliot and his title; COO of NCD.io,  to be added under the presenter's section in [this webinar page](https://flowfuse.com/webinars/2024/deploy-flowfuse-on-industrial-iiot-with-ncd-io/).  

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC [here's](https://drive.google.com/open?id=1ghG_fsLjhL0o9tmhYRHqOq-joNAaEi5m&usp=drive_fs) the image.

And you probably already know this, but in case you don't [here's](https://flowfuse.com/handbook/customer/marketing/webinars/#creating-a-webinar-page:~:text=webinar%20last%20for-,hosts,-A%20list%20of) a guide on how to add guests to the webinar page.
