### ISSUE TITLE
Blog: MIND Art

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#2012]
### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

MING
MQTT InfluxDB Node-RED Graphana

MIND
MQTT InfluxDB Node-RED Dashboards 2.0

This is the same concept but Dashboards 2.0 vs Graphana.

**Comment by Yndira-E** [comment]
Hi @gdziuba here it is 😉 


![Image](https://github.com/FlowFuse/website/assets/129537638/2cb44f3d-7241-4738-b6d6-5760945fc71a)
