### ISSUE TITLE
Update build workflow to pull from flowfuse main branch

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/website#2018]
### Description

With CI/CD now in operation, we should pull product docs from the `main` branch of the `flowfuse/flowfuse` repo, rather than the maintenance branch.

This task is to update the workflow to make it so.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
@ppawlowski Please also update the handbook where needed as part of this task
