### ISSUE TITLE
Data Flow Diagram for MIND blog

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#2029]
### Description

I would like a diagram that represents the flow of data from sensor to InfluxDB depicted below.

What comes to mind is a  simple flow diagram that in Node-RED like.

![image](https://github.com/FlowFuse/website/assets/8887166/b470eac3-ad2d-4d1c-87df-23845efcaa80)

The sensor should be a temperature sensor.

Sensor > Node-RED(FlowFuse Device Agent) > MQTT Encapsulated by FlowFuse > Node-RED(FlowFuse Platform) > InfluxDB

**Comment by Yndira-E** [comment]
@gdziuba the shapes in those diagrams have specific meanings, and I'm unsure which shape corresponds to each step. I came across this guide:

![image](https://github.com/FlowFuse/website/assets/129537638/9c65512b-4409-4578-a0b5-5d7536fc3d81)

If you could create a flowchart as you imagine it, even if it's not polished, drawn in Paint or Google Slides, using the appropriate shape for each step, I believe I could create a visually appealing image quickly.

**Comment by Yndira-E** [comment]
Before you created this issue, I didn't think you wanted a flowchart. I thought something more like the bottom part of this image:

![image](https://github.com/FlowFuse/website/assets/129537638/ab33e781-4e91-4c3d-9b2c-9ba6f46ef093)

Without background and title since this isn't a blog tile

**Comment by gdziuba** [comment]
@Yndira-E Can you do something like this:

![image](https://github.com/FlowFuse/website/assets/8887166/fd59d907-abf0-449a-b5e4-3a33b0e337af)

**Comment by Yndira-E** [comment]
@gdziuba here it is!

![Image](https://github.com/FlowFuse/website/assets/129537638/b26d5f2b-691d-414f-8b64-45cba96fb3b7)

**Comment by gdziuba** [comment]
@Yndira-E Can you remove the "Callout" from the Dashboard 2.0 reference?  That was my bad.

**Comment by Yndira-E** [comment]
@gdziuba there you go. Would you push it to the PR?

![Image](https://github.com/FlowFuse/website/assets/129537638/18683681-1bf0-493c-8f09-292ae0afc700)

**Comment by gdziuba** [comment]
Thank you.
