### ISSUE TITLE
Header image for 2.4 release blog

### ISSUE THREAD

**Issue by robmarcer** [FlowFuse/website#2033]
### Related Issue

https://github.com/FlowFuse/website/issues/2026

### Description

Suggested headlines for 2.4

Export Snapshots from FlowFuse
Easier creation of Node-RED instance from Blueprints
View Flows within the Team Library without loading Node-RED
View Flows within Snapshots without loading Node-RED

I'm waiting for @knolleary or @joepavitt's feedback, it should come at or before 12 once the release is done.

**Comment by robmarcer** [comment]
@Yndira-E the descriptions above have been approved from the header, thanks!

**Comment by Yndira-E** [comment]
Great! I'm working on it!

**Comment by Yndira-E** [comment]
@robmarcer 


![Image](https://github.com/FlowFuse/website/assets/129537638/dad02c35-bb03-41f8-a28e-29ccf9685b56)

**Comment by robmarcer** [comment]
Looks good, thank you.

**Comment by robmarcer** [comment]
Sorry about this, can we please add the following feature...

Managing Node-RED versions on Devices

**Comment by Yndira-E** [comment]
@robmarcer Updated image [here](https://drive.google.com/open?id=1ibovcmtUTzewWYjK_rmG1MzCmooOv9Al&usp=drive_fs)

**Comment by robmarcer** [comment]
Thanks
