### ISSUE TITLE
Blog Post: Product Mission Statement and Strategy Updates

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/website#2038]
### Related Issue

Not available yet

### Description

**Considerations:**
- Blog Post
- Focus on new "Build, Manage, Deploy" product pillars. Possibly a graphic/style for each?

**Comment by joepavitt** [comment]
This general structure would be really useful @Yndira-E, with some kind of supporting graphic for each of the three pillars

<img width="494" alt="Screenshot 2024-05-09 at 16 50 54" src="https://github.com/FlowFuse/website/assets/99246719/bc48c08c-a222-4608-90a6-4663912b034a">

**Comment by Yndira-E** [comment]
Hi @joepavitt here it is


![Image](https://github.com/FlowFuse/website/assets/129537638/eeafadd8-e53d-4cca-a52d-7d7ffe93da07)

And here's another option


![Image](https://github.com/FlowFuse/website/assets/129537638/1eb8f48a-98fd-4a26-907a-164902cd3229)

**Comment by joepavitt** [comment]
Love the 2nd one - think we can go a bit sharper/brighter on the font/images

**Comment by Yndira-E** [comment]
Like this?


![Image](https://github.com/FlowFuse/website/assets/129537638/23267c1f-4cb6-4ef6-8636-2f0c45d9b1d3)

It's [here](https://drive.google.com/open?id=1ioxlQEdTXdh3ara35YcZ8bcY0oPkv5Pm&usp=drive_fs) if you'd like to test out other colours

**Comment by joepavitt** [comment]
Spot on - great work as always @Yndira-E
