### ISSUE TITLE
Blog Art: Recreation of Tire Swing Analogy Art.

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#2060]
### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

**Inspirations:**
- <link here>
- <link here>

**Comment by gdziuba** [comment]
Can we recreate this artwork?

https://github.com/FlowFuse/website/blob/a3cc06e2f74ae5eb388843335e7bed3bce2b0393/src/blog/2024/05/images/tire-swing.png

**Comment by gdziuba** [comment]
1. How the customer explained it (Ladder on a tree - image 1)
2. How the Project Leader Understood it (image 2)
3. How the developer designed it (image 3)
4. How the application was developed (image 4)
5. What the customer really wanted Image 12)

The picture that mostly goes along with it.


![image](https://github.com/FlowFuse/website/assets/8887166/0a8d059e-02c4-44bd-947b-0dee7501be71)

**Comment by Yndira-E** [comment]
@gdziuba I've just pushed this one and the tile image to the PR


![Image](https://github.com/FlowFuse/website/assets/129537638/9c432d6c-ece6-4291-8206-51178f8f368c)
