### ISSUE TITLE
Blog Art: Setting up Node-RED on Raspberry Pi

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#2065]
### Related Issue

https://github.com/FlowFuse/customer/issues/204

### Description

Blog tile: Setting up Node-RED on Raspberry Pi

**Content reference:**

**https://github.com/FlowFuse/website/pull/2063**

**Comment by Yndira-E** [comment]
Hi @sumitshinde-84 here it is


![Image](https://github.com/FlowFuse/website/assets/129537638/6e3f1e7c-dd1b-4d19-9016-eff07fdf38b6)
