### ISSUE TITLE
Manufacturing whitepaper 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#2089]
### Description

Lead-gen piece of content targeting manufacturing industry leaders and decision-makers.  It will be linked from the manufacturing solution page to with a form to download. 

[Draft of white paper. ](https://docs.google.com/document/d/1TONzI_ZLWq8YZSjf03VRX0ms-0DjzdkmGKnSFr7KrwA/edit)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Hasmin-AC** [comment]
I have finalized the [whitepaper here](https://docs.google.com/document/d/1TONzI_ZLWq8YZSjf03VRX0ms-0DjzdkmGKnSFr7KrwA/edit#heading=h.qpra27bc0rgp)

@gdziuba I've added some suggested images, please confirm if they are good to go. 

@Yndira-E please design and create the page and the PDF version. 

This is the first of this type of content we are publishing. Let me know if you have any questions.

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC, in which section of https://flowfuse.com/solutions/manufacturing/ did you plan to link to that page? And what CTA should we add?

**Comment by Hasmin-AC** [comment]
CTA would be "Read Whitepaper". I'm thinking we place it in the intro section as a button as well as in the Resources section.

**Comment by Yndira-E** [comment]
@Hasmin-AC do you have a web page that I can use as an example for the design?
Are the website and the PDF supposed to have the exact same content? Or the web will be shorter? 
It's just that I found this example: https://www.gartner.com/en/digital-markets/insights/retain-and-expand-with-buyer-intent and it's more like our e-book page.

**Comment by Hasmin-AC** [comment]
@Yndira-E the garnter one is a example of a totalled gated piece of content. Its be more benefitial for us not to gate it as such so here are two examples of from [HiveMQ](https://www.hivemq.com/resources/hivemq-automotive-manufacturing-solutions-whitepaper/) and [WSO2](https://wso2.com/whitepapers/towards-a-precise-definition-of-microflows-distinguishing-short-lived-orchestration-from-workflows/)

**Comment by Yndira-E** [comment]
Thanks @Hasmin-AC!

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC 

The Google Docs file for the PDF format is ready, you can find it [here](https://docs.google.com/document/d/1R1k9iK5qTs0QqimdEGtPX7fdK8aR1gJyGXssW6cUikU/edit?usp=sharing).

Below is the static mockup, the page is really long, so maybe you'll get a better sense of it in [this quick prototype](https://www.figma.com/proto/3iuM4CG32oM3JNNmnDB7O5/FF-Website-V3---Blue-2024?page-id=0%3A1&node-id=3698-413&viewport=2975%2C-546%2C0.13&t=0uw2fAzc1xHXq2Ep-1&scaling=scale-down-width).



![Image](https://github.com/FlowFuse/website/assets/129537638/cbd01d67-8cb2-4622-8ea1-103d43561819)

Let me know your thoughts, so I can start working on the development of the page first thing in the morning.

**Comment by Hasmin-AC** [comment]
Thanks @Yndira-E. I think it might be good to reduce the case study sections to only quotes and link, so its not as long for the web page. I will highlight on the drafts document the text to keep.

**Comment by Yndira-E** [comment]
@Hasmin-AC you can check the updated prototype using the same link, and here's the updated image



![Image](https://github.com/FlowFuse/website/assets/129537638/03296907-0d6e-49b4-b7cc-d0196f4ce87a)

**Comment by gdziuba** [comment]
I like it.  It looks good.

**Comment by Hasmin-AC** [comment]
Lets remove the case study quotes from the Table of content though.
