### ISSUE TITLE
Blog art: Using MQTT with Node-RED

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#2104]
### Related Issue

#203

### Description

**Considerations:**
- blog tile:  Using MQTT with Node-RED

**content reference:**
- https://github.com/FlowFuse/website/pull/2100

**Comment by Yndira-E** [comment]
Hi @sumitshinde-84 here it is:


![Image](https://github.com/FlowFuse/website/assets/129537638/0f373ce2-2739-4bf4-ad97-1297278aca3e)
