### ISSUE TITLE
Update the values section on the homepage

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/website#2106]
### Description

We recently updated the homepage, but the values should reflect our Product Mission Statement and Strategy as well https://flowfuse.com/blog/2024/05/product-strategy-updates/

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
@Hasmin-AC as we talked about during our last department meeting, we should update that section. Could you please provide the content?

**Comment by Hasmin-AC** [comment]
@Yndira-E looking at the blog closely and what we have on home page, we don't need to update anything to align them. ZJ will however think about some other changes we need to make to update our messaging.

**Comment by Yndira-E** [comment]
Thanks for the update!
