### ISSUE TITLE
Landing page for Dashboard 2.0

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#2131]
### Description

overview page about Dashboard 2.0 that we can use to promote it. 

Here's the [draft content. ](https://docs.google.com/document/d/10k1kbhL6_wKHMvXk63B2teTZYY6PZn9v46mxwN1rYDw/edit).

@joepavitt and @ZJvandeWeg Please provide any additional points to highlight. 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Just curious - what's the purpose of this vs. https://dashboard.flowfuse.com?

**Comment by ZJvandeWeg** [comment]
@joepavitt Landing page is intended to be high level, dashboard.flowfuse.com should be docs only as it's now.

**Comment by Hasmin-AC** [comment]
@Yndira-E can you please create this landing page? Content is [here](https://docs.google.com/document/d/10k1kbhL6_wKHMvXk63B2teTZYY6PZn9v46mxwN1rYDw/edit#heading=h.xkee3a6rrpvf)

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC 

![Image](https://github.com/FlowFuse/website/assets/129537638/af721b69-0ddd-4fee-9d31-e87be1abcbb8)

I think I could create an animated loop for the hero image.

For the migration section, maybe it would be good to add a short description to set expectations. I'm guessing users would receive a file in their email inbox, right?

And, for the learning resources:

- I'll update the image for the second item.
- I'm unsure about the third item. Is there an ebook with dashboard content available yet?

**Comment by Hasmin-AC** [comment]
Looks good @Yndira-E. 

An animated loop will be cool. Should the graphics have some node-red/FF branding on it though, so it looks close to the actual dashboards which are supposed to be visually appealing themselves? 

ebook is on the way and should be ready by next week or so.

**Comment by joepavitt** [comment]
> Should the graphics have some node-red/FF branding on it though, so it looks close to the actual dashboards which are supposed to be visually appealing themselves

Worth noting Dashboards have no FF/NR branding on them, which is one of the reasons they're popular. Users can brand them in their own way.

**Comment by Hasmin-AC** [comment]
I see. My point was also to have something less abstract because it is a visual tool that can be showcased.

**Comment by joepavitt** [comment]
> My point was also to have something less abstract because it is a visual tool that can be showcased.

Ah, in that case, I'm all for it. We can start off with Yndira's as it's already ready to go, but to make a mock/realistic looking Dashboard would be fairly easy to do, and agree, better to show real-value, rather than pseudo-graphics where possible

**Comment by Yndira-E** [comment]
@Hasmin-AC, what about this:

> For the migration section, maybe it would be good to add a short description to set expectations. I’m guessing users would receive a file in their email inbox, right?

Regarding the dashboard image, @joepavitt, how could we create a more realistic one? Screen recording an actual dashboard? The pseudo graphic seemed like a good idea because it’s industry-agnostic. What kind of ‘data’ do you guys think we should showcase?

I was thinking, if we’re going to add numbers and titles, maybe the titles could be changing so they don’t relate exclusively to any industry.

If it’s going to be animated, I’ll need some input because I’m not sure what type of data each industry is interested in displaying on dashboards.

**Comment by joepavitt** [comment]
I think it can still be industry-agnostic. I think Hasmin's point is to make it look more like a real Dashboard generated by D2.0

**Comment by Hasmin-AC** [comment]
@joepavitt can you please help with the text for the migration section?

**Comment by joepavitt** [comment]
> I'm guessing users would receive a file in their email inbox, right?

That was the plan, but HS doesn't make this easy, or even possible, without paying an additional $600/month. As such, I've built in a workaround that means, they need to fill in the form, but will just have the file downloaded through the browser.

> can you please help with the text for the migration section?

For now, let's go with:

_"Get started quickly with your new Dashboard 2.0. This migration service will automatically convert your original Node-RED Dashboard flows, and make them Dashboard 2.0-ready"_.

We should add an asterisk, with the following note:

_"This service will improve over time. Currently, we support the automatic conversion of `ui_tab`, `ui_link` and `ui_group` nodes"_

**Comment by Yndira-E** [comment]
Thanks!

This is an updated version with the incorporated text into the migration section:

![Image](https://github.com/FlowFuse/website/assets/129537638/493d1978-6fad-47d7-bf85-6964976357d9)

Do we have a ETA for the ebook?

**Comment by ZJvandeWeg** [comment]
@Yndira-E Having spoken to Nick a couple of times, we might want to rebrand D2.0 to just "FlowFuse Dashboard". That removes the weird branding we got right now. The Headline for the page IMO should already be "FlowFuse Dashboard for Node-RED".

**Comment by Hasmin-AC** [comment]
@ZJvandeWeg are we dropping the 2.0 part as well?

**Comment by Yndira-E** [comment]
I think we are...

![Dashboard 2 0_](https://github.com/FlowFuse/website/assets/129537638/958e6f9d-e23a-49e7-ad52-af10128b5afb)

**Comment by Hasmin-AC** [comment]
@Yndira-E we'll have to update the text parts as well but I can do that once the PR is created.

**Comment by Yndira-E** [comment]
@Hasmin-AC I've just updated the image in my previous comment, I think I replaced all the Dashboard 2.0 references, we will have to update the titles of the learning resources as well.

**Comment by Hasmin-AC** [comment]
Ebook PDF is ready. See https://github.com/FlowFuse/customer/issues/146
