### ISSUE TITLE
Blog: How to build out a multi-user dashboard on Node-RED Dashboard 2.0 with FlowFuse

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#2134]
### Description

Summary of the demo on the webinar: https://flowfuse.com/webinars/2024/node-red-dashboard-multi-user/

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by sumitshinde-84** [comment]
Should this issue be closed, @Hasmin-AC?
