### ISSUE TITLE
June Webinar Art 

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#2137]
### Description

Title: Building a foundation for Enterprise Agility and Process Optimization
Date/time: June 26th, 17:00 CET (11:00 ET)
Name of hosts: Grey Dziuba
Title/job description of each host:

Grey Dziuba - OT Data and Community Strategist

**Comment by Yndira-E** [comment]
Hi @gdziuba here it is!

![Image](https://github.com/FlowFuse/website/assets/129537638/0b468a88-ad89-4421-9ccf-0ceba1b24eb0)

**Comment by gdziuba** [comment]
Date is wrong.  Can you adjust?

**Comment by Yndira-E** [comment]
Sorry! Here it is


![Image](https://github.com/FlowFuse/website/assets/129537638/bc267d73-7285-491c-b14d-517a1020e0fa)

**Comment by gdziuba** [comment]
Thank you.

**Comment by Yndira-E** [comment]
Do you think the webinar page will be ready today? Or should I move the content scheduled for Thursday to tomorrow?

**Comment by gdziuba** [comment]
I am looking to get it completed today
