### ISSUE TITLE
Art Request: Release Highlights v2.5

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/website#2138]
### Description

Release Highlights Tile for v2.5

- Support for LDAP integration
- Preview Blueprints before Deployment
- Compare Snapshots Visually to see differences
- Import and Export support for snapshots
- Deploy Dashboard and APIs running on Flowfuse via your own Domain Names

**Comment by Yndira-E** [comment]
Hi @gdziuba here it is!

![Image](https://github.com/FlowFuse/website/assets/129537638/be5dc37c-41af-4fc9-bfcc-b84782316448)

**Comment by gdziuba** [comment]
Thank You
