### ISSUE TITLE
Blog Art: Using TimescaleDB with Node-RED

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#2150]
### Description

Blog Tile : Using TimescaleDB with Node-RED

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

**Content reference**
- https://github.com/FlowFuse/website/pull/2116

**Comment by Yndira-E** [comment]
Hi @sumitshinde-84 here it is


![Image](https://github.com/FlowFuse/website/assets/129537638/ddd807f8-b6ac-49b0-9577-e5b001942b92)
