### ISSUE TITLE
Blog Tile: "Changes to Multi-Tenancy in Node-RED Dashboard 2.0"

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/website#2182]
### Related Issue

https://github.com/FlowFuse/website/pull/2181

### Description

**Considerations:**
- Blog Tile

**Inspirations:**
- Doesn't need to be too fancy, security themed, with user icons thrown in there too I guess?

**Comment by Yndira-E** [comment]
Hi @joepavitt would this work?

![Image](https://github.com/FlowFuse/website/assets/129537638/43d2b467-fc81-43d6-b988-34cc15f15f30)

**Comment by joepavitt** [comment]
Ideal - thanks @Yndira-E
