### ISSUE TITLE
Create a landing page for /node-red/*

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/website#2186]
### Description

We have a learning resources section on the `/node-red `page
<img width="1105" alt="Screenshot 2024-06-13 at 10 28 22" src="https://github.com/FlowFuse/website/assets/129537638/f33a0527-2ce3-405a-80ec-78a6f32a007d">

The `see more` button links to https://flowfuse.com/blog/node-red/ but we're building some node-red documentation that have no way to be linked to unless linked to a specific resource, like the core-nodes for instance.

We should create a `/node-red/learning-resources` or `node-red/docs`? (open to suggestions) landing page to link to in a generic way, like here you'll find all the docs or resources.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by sumitshinde-84** [comment]
@Hasmin-AC, @ZJvandeWeg @Yndira-E  I want to ask about the Node-RED Learning Resources page URL. How about using `/node-red/learn/`? It is short and SEO-friendly.
