### ISSUE TITLE
Landing page for Cloud 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#2188]
### Description

This page is meant to provide an overview about FlowFuse Cloud. It'll serve as the landing page for ads and places where we'd want to provide a link to our cloud offer. 

Content for this page can be found [here](https://docs.google.com/document/d/1vLWlt4855YXPEW0YS9U8qVvgfOdQCV0odziGgIw-EYE/edit)

@robmarcer can you please add any other FAQ questions that you think would be good to list here? 

@ZJvandeWeg for any other input on the content. 

@Yndira-E Can you please work on the design? I'd like to get an updated video similar to what we have on the Features page on how to get started. Let me know if you need anything from me to create that. We can use pretty much the same narrative, just with FlowFuse instead of FlowForge :) 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
@Hasmin-AC Can you provide an outline? I don't understand what you want from me in this issue.

**Comment by Hasmin-AC** [comment]
@ZJvandeWeg Any general feedback on the cloud positioning and faq of the landing page before Yndira works on the design.

**Comment by ZJvandeWeg** [comment]
FlowFuse Cloud positioning:
- Centrally manage your Node-RED instances, even when hosted on-site
- Reduce operational load to set up and maintain Node-RED
  - Cloud hosted Node-RED without the need to touch NGINX, Docker, etc. Custom domains are supported.
- Unlock collaboration - Team based development and shared responsibility
- Follow best practices security: SSO for Authentication, RBAC for authorization.

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC 

In the section:

> [Sub title ] Focus on Your Flows, Not the Setup
> [3 boxes side by side] 

The text is long and not all three are the same length, it would look like this (ignore the icons, I still need to update those):

![Image](https://github.com/FlowFuse/website/assets/129537638/5465320d-8586-484b-ad6b-168101524a06)

Could you shorten at least the second and third ones to match the length of the first one?

_(I tried to add a comment on the doc, but I only have viewers permission.)_

**Comment by Yndira-E** [comment]
This is the full page with the content as it currently is.

![Image](https://github.com/FlowFuse/website/assets/129537638/b3387a3b-ad92-4fd1-ae91-b5345f5b80cc)

Who's going to record the new video? Do we have an ETA?

**Comment by Hasmin-AC** [comment]
@Yndira-E here's the shortened text for the Security section "Your data security is our top priority. FlowFuse Cloud employs a multi-layer security approach, ensuring protection at every level, including Role-Based Access Control (RBAC) for granular permissions and Single Sign-On (SSO) for secure access. Our SOC 2 Type 1 compliance demonstrates our commitment to upholding rigorous security standards." 

Is it possible to make the testimonials bigger so it stands out more? maybe bigger font and one under the other? 

Lets also add a CTA at the bottom says "Have more questions? Contact us and we'll be happy to help"

**Comment by Hasmin-AC** [comment]
Lets go live with the current video and update it later.

**Comment by Yndira-E** [comment]
> Is it possible to make the testimonials bigger so it stands out more? maybe bigger font and one under the other?

Hi @Hasmin-AC, it is possible, but I feel that if we make it bigger, it would mess with the content hierarchy, making it look like the most important thing on the page. It would look like this:

![Image](https://github.com/FlowFuse/website/assets/129537638/2521c615-a71f-49d0-a627-3617f033db1b)

How about adding some background colour instead?


![Image](https://github.com/FlowFuse/website/assets/129537638/c3db1756-0959-4ada-a811-862a2796101b)

**Comment by Hasmin-AC** [comment]
One under the other works better I think, but can we drop the square outlines and increase the width?

**Comment by Yndira-E** [comment]
@Hasmin-AC 
![Cloud](https://github.com/FlowFuse/website/assets/129537638/92270851-8371-4328-97db-08a390dc925f)

**Comment by Hasmin-AC** [comment]
Lets get this live! Thanks @Yndira-E

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC, you mentioned this would go under the product menu. The doc says the URL should be `flowfuse.com/cloud`, is that correct? Or should it be `flowfuse.com/product/cloud` instead?
