### ISSUE TITLE
Blog Art:  How to Filter, Map, Sort, and Reduce Data in Node-RED

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#2214]
### Description

**Considerations:**
- Blog Tile:  How to Filter, Map, Sort, and Reduce Data in Node-RED

**content reference:**
https://github.com/FlowFuse/website/pull/2203

**Comment by Yndira-E** [comment]
Hi @sumitshinde-84 I've just pushed it to your branch


![Image](https://github.com/FlowFuse/website/assets/129537638/d26fda26-0c12-4a26-958d-2a6ae6cbfd81)

**Comment by Yndira-E** [comment]
https://github.com/FlowFuse/website/pull/2203#discussion_r1648570362

**Comment by Yndira-E** [comment]
Updated version


![Image](https://github.com/FlowFuse/website/assets/129537638/448096f8-de9c-4cf9-9f5e-b67db7f758e7)
