### ISSUE TITLE
Blog Art: How to call python script from Node-RED

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#2215]
### Related Issue

https://github.com/FlowFuse/customer/issues/206

### Description

**Considerations:**
- Blog tile :  How to call Python script from Node-RED

**Content reference:**
https://github.com/FlowFuse/website/pull/2210

**Comment by Yndira-E** [comment]
Hey @sumitshinde-84 I've just pushed it to your branch


![Image](https://github.com/FlowFuse/website/assets/129537638/bc09465b-277a-4c93-8d94-bf959c070b51)
