### ISSUE TITLE
Blog Art: Node-RED 4: Bringing better collaboration to FlowFuse Cloud

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/website#2219]
### Related Issue

https://github.com/FlowFuse/website/pull/2218

### Description

**Considerations:**

Blog post announcing Node-RED 4.0 is available on FFC and the collaboration features it unlocks.

Title: Node-RED 4: Bringing better collaboration to FlowFuse Cloud

Draft in https://github.com/FlowFuse/website/pull/2218

**Comment by knolleary** [comment]
@Yndira-E sorry for the nudge, but we're on track to publish the release later today, so would like to have the blog post ready to go soon after.

**Comment by Yndira-E** [comment]
@knolleary on it!

**Comment by Yndira-E** [comment]
I've just pushed it to your branch


![Image](https://github.com/FlowFuse/website/assets/129537638/9bc607ba-8a9c-4f7b-bf2a-ccda968a1a6b)
