### ISSUE TITLE
Blog: White Labelled Dashboards

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/website#2221]
### Description

**Content Overview:**

- Recently released a [new feature](https://dashboard.flowfuse.com/nodes/widgets/ui-template.html#page-name-app-bar-title) in Dashboard 2.0 that means we can replace the main page title with custom content.
- Given this, we can now provide full customisation over the theming/styling of a Dashboard, and even have developers add their own company logos, etc.
- Content would upsell Dashboard for commercial purposes

Specifically, we want to ensure we cover:

- Adding company logo to app bar title ([docs](https://dashboard.flowfuse.com/nodes/widgets/ui-template.html#page-name-app-bar-title:~:text=Here%2C%20we%20can%20render%20an%20image%20(injected%20via%20msg.payload)%20instead%20of%20the%20page%20name%3A))
- Show some level of user login/plugin as we've seen in other articles (detailed [here](https://github.com/FlowFuse/node-red-dashboard-2-user-addon?tab=readme-ov-file#showing-user-info))
- Show how we can modify the general theme of a Dashboard (using the "Themes" tab in the NR Editor)

### Are there any pricing considerations?

N/A

### Are there any website updates that need to be made?

N/A

### Demo Link

N/A

**Comment by joepavitt** [comment]
Not sure the "White Labelled Dashboards" is the correct terminology, I'd be keen to get @Hasmin-AC's opinion here as it shouldn't be too technical.

**Comment by joepavitt** [comment]
"Customise theming in your Dashboards" could be an alternative approach

**Comment by Hasmin-AC** [comment]
@sumitshinde-84 Can you please work on this blog?

**Comment by joepavitt** [comment]
We _may_ be looking to add a new feature here that would help this even further: 

https://github.com/FlowFuse/node-red-dashboard/issues/1060

Adding static assets into FlowFuse hosted Node-RED is not a trivial task right now, but I don't have a timeline on 1060.

@knolleary if someone wants to "upload" a company logo to static file store on NR right now (in FF), what is the best method? Hoping the file persistence helps us here? (And means we can upsell that feature too in this blog)
