### ISSUE TITLE
Blog Art : interacting with Google sheet from Node-RED

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#2226]
### Related Issue

https://github.com/FlowFuse/website/pull/2223

### Description

**Considerations:**
- Blog tile: interacting with Google sheet from Node-RED

**Inspirations:**
https://github.com/FlowFuse/website/pull/2223

**Comment by Yndira-E** [comment]
Hi @sumitshinde-84 

![Image](https://github.com/FlowFuse/website/assets/129537638/dc082653-c08e-4d1f-aca8-ee06d90b6840)
