### ISSUE TITLE
Marketing Page: Device Agent

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/website#2236]
### Description

**As a:** FlowFuse Employee

**I want to:** have a marketing resource that I can share about our "Device Agent"

**So that:** we can better communicate what the customer value of the device agent is, without needing to link to technical/overwhelming documentation.

We are quite vague on our website about edge agents, etc. Having an explicit page I could link to when [leads come up](https://discourse.nodered.org/t/dashboard-2-gather-data-from-multiple-dropdowns-on-multi-tenant-dashboard/88838/2) would be really useful.

### Acceptance Criteria

- [ ] Emphasising how lightweight the agent is
- [ ] Remote management and deployment of Node-RED instances
- [ ] Easy deployment/updating of flows
- [ ] Centralised management of thousands of "devices"

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by sumitshinde-84** [comment]
We do have newly created documentation available [here](https://flowfuse.com/node-red/hardware/) that currently provides resources on setting up Node-RED on various hardware devices, using different databases, protocols, notification services, and integration technologies. This section will be expanded further, but I think you are referring to something more specific. Should that be added to this new documentation?

**Comment by joepavitt** [comment]
I don't think its documentation we need, more of a landing page for Device Agent to advertise it's value/feature. Similar to what we are doing for Dashboard with flowfuse.com/dashboard

**Comment by sumitshinde-84** [comment]
Thanks @joepavitt, now I understood !

**Comment by joepavitt** [comment]
We should also update this link on the Manufacturing page to point to the new landing page:

<img width="1061" alt="Screenshot 2024-06-27 at 14 35 08" src="https://github.com/FlowFuse/website/assets/99246719/7a00fd19-68df-4767-bb5a-bea9ada644d3">

**Comment by Hasmin-AC** [comment]
@joepavitt We have [this page about Edge Device Management ](https://flowfuse.com/solutions/device-management/) Is this pretty much the same content we would have for a page on Device Agent? 

Should we just update this page rather than create a new one?

**Comment by joepavitt** [comment]
I think the existing page is more about the general use case for edge device management, which encompasses the story of FlowFuse, Device Agent, Project Nodes and even Dashboard.

For this new page, we want it focussed on the Device Agent offering, a little more technical than the other page, but not too much. Focus on what it enables, it's ease of use (maybe even a pseudo-demo animation - which I can storyboard)

**Comment by Hasmin-AC** [comment]
Got started on some draft content.  I didn't have too much to go on so would be great if you can add more specific details to this doc - https://docs.google.com/document/d/1-brzrhsxGImHqNt6lUwiKq0UdTWQXqmQzL7QDeQkTC4/edit

**Comment by joepavitt** [comment]
> I didn't have too much to go on

Exactly why we're needing this page, as nor do our customers! I've requested access to the file

**Comment by Hasmin-AC** [comment]
Done

**Comment by joepavitt** [comment]
Thanks @Hasmin-AC I've added comments and suggestions. The key here (which is a big confusion for customers too) we have:

- Device Agent
- Project Nodes

The agent is the piece that's installed onto devices/hardware and allows for remote management/deployment of Node-RED instances to that hardware, via FlowFuse.

The nodes are then what allow for easy collection of that remote data back to centralised instances on FF Cloud for example.

**Comment by joepavitt** [comment]
I've _very quickly_ put a storyboard together for the video/animation too:

<img width="1275" alt="Screenshot 2024-07-18 at 12 07 24" src="https://github.com/user-attachments/assets/1f1b9a54-456f-40b6-ab13-735c9b9ba994">

Emphasis probably at the end here too on how this can then be deploy out to hundreds of devices, not just the one.

Storyboard is in https://www.figma.com/board/wOZC4A72Q48AAWcUe0uoF3/Storyboard---Device-Agent-Animation?node-id=0-1&t=A4LZjPcomIPeEowP-1

**Comment by joepavitt** [comment]
maybe even the terminal behind FlowFuse UI here, this is from the Mongo homepage:

https://github.com/user-attachments/assets/dda3154a-5ef0-40c8-9e94-d14e2489ab31

**Comment by Yndira-E** [comment]
Here's the design:



![Image](https://github.com/user-attachments/assets/0cf1f3b5-261d-43e4-89b4-3855442b6a68)




For the video, we're adding [this one](https://drive.google.com/open?id=1ifsagVfEXDVOPOYzGMV40gREtMcmxZLp&usp=drive_fs) until the new one is ready.

And we still need the FAQs, but those can be added in the PR.

**Comment by joepavitt** [comment]
The "Seamlessly" header/line I think could be a bit different, as it's not the true value of the device agent here. "Seamlessly manage your devices all in one place" is the value of the agent/flowfuse crossover

**Comment by Yndira-E** [comment]
Noted, Joe. Thanks for the suggestion.
The doc says: `Url: flowfuse.com/device-agent`.
But since "cloud" and "dashboard" are under `/product/*`, would it make sense to add this one to the same route?

**Comment by joepavitt** [comment]
> But since "cloud" and "dashboard" are under /product/*, would it make sense to add this one to the same route?

Most certainly
