### ISSUE TITLE
Remove meeting calendar from the thank-you page template

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/website#2244]
### Description

The meeting link will be sent by the respective AE the lead is assigned to.

### Epic/Story

https://github.com/FlowFuse/website/pull/2243

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC we have two templates for thank you pages:

1. The one you were trying to change, related to downloadable content:
![image](https://github.com/FlowFuse/website/assets/129537638/2ac2b57f-b63a-48e2-bb67-6cd28ccf9fcc)

I'm assuming we'll also remove the text that says "See how FlowFuse can help with your next project. Book a call now"

This would only leave us with the three first lines of text, and the "latest on the blog" section.

2. And this one:
![image](https://github.com/FlowFuse/website/assets/129537638/0a50fb91-c6f5-4242-9b30-ad8a2aa98168)

For this one, if we remove the calendar, we would only have the thank you text and customer logos.

Is this what you had in mind?

**Comment by Hasmin-AC** [comment]
Lets replicate the CTA section on the home page (Latest on the blog, webinar, newsletter) here instead of Calendar. Lets place this this right below the thank you messages on both templates followed by customer logo section. thanks!
