### ISSUE TITLE
Make Products Menu two columns 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#2250]
### Description

It would be good to make the Product menu drop down be two columns and move Dashboard to the right hand side. This would give it a little more prominence. We can list Cloud on that side too. 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Thank you for the suggestion! This change will actually be part of the updates I'll be implementing when creating the Cloud landing page, so there's no need for a separate issue.

I always aim to keep single columns to a maximum of 5 items, so splitting the Product menu into two columns as we add more items is the natural approach. Rest assured, the Dashboard and Cloud items will get the prominence they deserve.
