### ISSUE TITLE
Node-RED Icon: For AI operations

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/website#2258]
### Related Issue

AI Function Node Iteration [#4073](https://github.com/FlowFuse/flowfuse/issues/4073)

### Description

Following a chat with @joepavitt we identified a need for a new ICON for use in node-red (and potentially other places, but initially Node-RED)

The outline is we need a button icon (might be used in a menu or a form also) that upon being clicked, would open a text input where a user can enter a prompt for AI to generate code/flows. The icon should infer this.

**Considerations:**
- For use in Node-RED editor
- Should be SVG or PNG
  - If PNG, different sizes 26x26, 32x32, 48x48

**Inspirations:**
- Something that blends  chat + brain/lightbulb + intelligence
  - some good ideas in  https://carbondesignsystem.com/elements/icons/library/ under AI + senses + chat

I am sorry we cannot be more specific (we are looking for inspiration) so 3 very quick unique mock ups might be a good starting point. They can be super simple PNG sketches that we can evaluate and fine tune and eventually chose a "winner" that gets finalised in SVG?

Really looking for inspiration.

**Comment by Yndira-E** [comment]
Hi @Steve-Mcl I've put together these:

![AI icon](https://github.com/FlowFuse/website/assets/129537638/8612126e-882e-48b7-8696-782f987377a3)

Decided to add them to the bar so you can see it in context. Let me know if any of those seem like a good fit.

**Comment by joepavitt** [comment]
Love the second option

**Comment by Steve-Mcl** [comment]
Thank you and great stuff as always Yndira.

I am indifferent to the offerings as they all look great (and are far better than i could do) so will discuss with Joe once he has had a chance to play with the new nr-assistant 

for now i will attach this to a new task issue in the repo so it doesnt slip.

**Comment by Yndira-E** [comment]
I've exported them all as SVGs to https://drive.google.com/open?id=1uBit1wsAxoGH06QvKVcE7rib9Bzmt5Qq&usp=drive_fs

**Comment by Steve-Mcl** [comment]
@knolleary are you also in favour of the 2nd one?

![image](https://github.com/user-attachments/assets/6963f42a-f7ff-41ca-b38f-4c22cc9c0e9e)

**Comment by knolleary** [comment]
@Steve-Mcl yup, either 2 or 3 - happy to go with either
