### ISSUE TITLE
Webinar: Bringing AI to Node-RED with FlowFuse Assistant

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/website#2277]
### Description

**Considerations:**
- Webinar tile for https://github.com/FlowFuse/website/pull/2276

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-E** [comment]
Hi @knolleary I've just pushed it to your branch.

![webinar-2024-july](https://github.com/FlowFuse/website/assets/129537638/b395a269-7ab4-4748-a293-07f46876a129)
