### ISSUE TITLE
Dashboard landing: Add a Dashboard + FlowFuse section

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/website#2279]
### Description

Add a section highlighting the benefit or the power of the FlowFuse + FlowFuse dashboard package

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
@joepavitt could you please help me out with the text? Just adding a comment here would be enough, I'll take care of the web

**Comment by joepavitt** [comment]
I'm not great with words, but that's _something_

**Comment by Yndira-E** [comment]
Thanks Joe!!
