### ISSUE TITLE
Changelog entry for Multiline Env Vars

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/website#2291]
### Description

See [issue](https://github.com/FlowFuse/flowfuse/issues/3972) / [PR](https://github.com/FlowFuse/flowfuse/pull/4069) for reference

### Epic/Story

https://github.com/FlowFuse/flowfuse/issues/3972

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
What I've written for this on our release blog:

> We now support the use of multi-line environment variables for your Node-RED instances running on FlowFuse. This unlocks the ability to store certs or multi-line values like JSON as environment variables. We've also improved the `.env` importing to support the use of multi-line values too.
