### ISSUE TITLE
Images for OSS whitepaper

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/website#2301]
### Related Issue

https://github.com/FlowFuse/website/pull/2295#issuecomment-2210535103

### Description

**Considerations:**
Create additional visual aids to drive some points in https://flowfuse.com/whitepaper/open-source-software-for-manufacturing/
Add them to the GDoc: https://docs.google.com/document/d/156UXE-v-Ko0qL-z0syHKi8d68JzUtxoY7piDIeXe8RQ/edit?usp=sharing

**Inspirations:**
- <link here>
- <link here>

**Comment by Yndira-E** [comment]
@Hasmin-AC, ZJ said about this whitepaper:

> @Yndira-E @Hasmin-AC I appreciate the iteration. I think it would serve the content if there's additional visual aids to drive some points. Would you be able to read the content and think of such visuals?

I've added some images to the Google doc, please check it out and let me know what you think.

**Comment by Hasmin-AC** [comment]
I like the open source one. 

For the placement for the images under "Risks and Remedies for Open-Source Software in Manufacturing", might be better if each image is next to that section. Not sure if that was your plan too.

**Comment by Hasmin-AC** [comment]
If thats the best option lets go ahead then.

**Comment by Yndira-E** [comment]
For the sub-section that says `Here are some other risks and remedies to consider:`, how about presenting the content as a table instead? It would be easier to scan than the paragraphs we currently have and we wouldn't need the images. Something like:

### Risk Matrix for Using Open Source Software (OSS) in Manufacturing

| Risk                         | Description                                                                                          | Impact | Probability | Remedy                                                                                                           |
|------------------------------|------------------------------------------------------------------------------------------------------|--------|-------------|------------------------------------------------------------------------------------------------------------------|
| Legal and Procurement        | Risk of adopting licenses that do not comply with internal policies, especially those requiring publication of modifications. | Medium | Low         | Conduct internal license reviews and obtain legal advice to ensure licenses comply with corporate policies.     |
| Hard Hat Safety              | Malfunctions in real-time control software can lead to severe consequences in manufacturing settings. | High   | Moderate    | Implement rigorous testing, validation, and redundancy mechanisms to ensure reliability and safety in manufacturing environments. |
| Black Hat Safety             | Users are responsible for patching and updates, leaving systems vulnerable to cyberattacks if not managed properly. | High   | High        | Establish a robust patching process, use automated tools for dependency management, and follow secure coding practices. |
| Maintenance and Support      | OSS lacks formal support channels, leading to longer resolution times.                              | High   | Moderate    | Establish relationships with OSS expert providers, use professional services, and ensure proper training.        |
| Professional Services        | Engaging consultants or service providers for OSS security and training.                            | Medium | Moderate    | Utilize professional services for risk assessments, vulnerability management, and incident response; provide targeted training for staff. |
| Adaptation and Compatibility | Lack of compatibility with existing systems and hardware can slow adoption and generate additional costs. | Medium | Moderate    | Use OSS with an active community and broad ecosystem; conduct thorough compatibility testing before implementation. |
| Contribution Costs           | Active participation in the OSS community can be costly in terms of time and resources.             | Medium | Moderate    | Collaborate with OSS providers who manage contributions and maintain the software; adopt an incremental approach to contributions. |
| Transparency and Reviews     | Transparency allows for constant review but may make the software more susceptible to attacks if not regularly reviewed. | High   | Moderate    | Maintain continuous review and update processes, and collaborate with the community for timely detection and resolution of vulnerabilities. |

### Explanation of Impact and Probability

- **Impact:**
  - **High:** Can cause significant disruptions in operations, equipment damage, or safety risks.
  - **Medium:** Can cause some delays or additional costs but does not severely disrupt operations.
  - **Low:** Has a minor and manageable effect on daily operations.

- **Probability:**
  - **High:** Likely to occur frequently.
  - **Moderate:** May occur occasionally.
  - **Low:** Unlikely to occur but cannot be ruled out.

This matrix provides a clear view of the risks associated with adopting OSS in manufacturing and the measures that can be taken to mitigate them, helping organizations make informed decisions.

**Comment by Hasmin-AC** [comment]
Good idea @Yndira-E it will break up the text blocks as well.

**Comment by Yndira-E** [comment]
@Hasmin-AC, I hope you're doing well! I've left a comment on the document asking if you could please review the content and make any changes you think are needed. After that, could you export the PDF and update it in HubSpot? Just let me know when it's done, and I'll go ahead and update the web page too. Thanks!
