### ISSUE TITLE
Each page should have lang attribute  

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#2303]
### Description

The "lang" attribute sets the page language. Screen readers rely on this information to determine which language library to use.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
@sumitshinde-84 Do you have an example of pages that don't have a lang attribute? I think `base.njk` always sets it?

**Comment by sumitshinde-84** [comment]
@ZJvandeWeg, correct ! The `base.njk` file sets the lang attribute. closing this issue
