### ISSUE TITLE
Optimize Loading Time of Video Embed on Homepage

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#2306]
### Description

The video embedded on the homepage currently takes 10,230 ms to load, impacting the Largest Contentful Paint (LCP). To improve performance, it should be lazy-loaded to optimize initial page load times. Additionally, the background GIF image used in the `<lite-youtube>` element is 1,093.2 KiB, which is quite large and should be optimized.

https://github.com/FlowFuse/website/blob/b5279cadc11f67548ff153058efc9a909feac732/src/index.njk#L40

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hey @sumitshinde-84 I was just looking into this today. How about using https://github.com/paulirish/lite-youtube-embed instead? apparently it loads faster than lite-youtube
And this is also used in other pages:
- Features
- Cloud
- Device management
