### ISSUE TITLE
Blog Art : Deploying FlowFuse with Docker on the Ubuntu server

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#2338]
### Description

**Considerations:**
- Blog tile 

**Content reference:**
- https://github.com/FlowFuse/website/pull/2300

**Comment by Yndira-E** [comment]
Hi @sumitshinde-84 here it is

![Image](https://github.com/user-attachments/assets/d7f7b35c-465b-4c80-9a1b-1f4ec0fabe57)
