### ISSUE TITLE
Blog Art: How to Set Up SSO SAML for Node-RED

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#2341]
### Description

**Considerations:**
- Blog tile

**Content reference:**
- https://github.com/FlowFuse/website/pull/2336

**Comment by Yndira-E** [comment]
Hi @sumitshinde-84 



![Image](https://github.com/user-attachments/assets/85dd7865-9acb-4af8-9e74-b99f51a3d763)
