### ISSUE TITLE
Blog Tile: "Building on FlowFuse: Remote Device Monitoring"

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/website#2343]
### Related Issue

https://github.com/FlowFuse/website/pull/2264

### Description

**Considerations:**
- Blog tile
- "Building on FlowFuse" will be the series/theme of the article, so should appear first, but in smaller and more discrete font - the highlight/title focus should be on "Remote Device Monitoring"

**Inspirations:**
- Please use the "Use Case" architecture diagram in the tile, the one with the read, parse, compute, action, etc.

**Comment by Yndira-E** [comment]
Hi @joepavitt, I took the image from the PR, but it's a bit small for [the tile](https://drive.google.com/open?id=1wHI1rUKF_FyligV4lvoQ45Hd0uivhFfz&usp=drive_fs). Where can I find the vector diagram? I looked [here](https://www.figma.com/design/3iuM4CG32oM3JNNmnDB7O5/FF-Website-V3---Blue-2024?node-id=198-1247&t=8x7scXi0kFtRi6s0-1) and in the old web Figma too, but no luck.

**Comment by joepavitt** [comment]
It's under the "Diagrams" folder: https://www.figma.com/design/hYBXEnFKVUii0mLwjuhM0M/FF-Design-Pattern---Device-Monitoring?node-id=0-1&t=oURynrUMvSIoMFqi-1

**Comment by Yndira-E** [comment]
Thanks Joe!! Here's the tile:

![Image](https://github.com/user-attachments/assets/c69572fd-ab05-4e3d-a231-a614ec862d32)
