### ISSUE TITLE
Blog Art: How to Set Up SSO LDAP for Node-RED

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#2377]
### Description

**Considerations:**
-  Blog Tile : How to Set Up SSO LDAP for Node-RED

**reference:**
- https://github.com/FlowFuse/website/pull/2345

**Comment by Yndira-E** [comment]
Hi @sumitshinde-84 

Same kind of content as https://flowfuse.com/blog/2024/07/how-to-setup-sso-saml-for-the-node-red/ so I thought we could use the same base 😉 

![How-to-Set-Up-SSO-LDAP-for-Node-RED](https://github.com/user-attachments/assets/9f904cab-c1e3-42ff-8cf2-37a6fb3f5082)
