### ISSUE TITLE
Blog Tile: New Charts Available in FlowFuse Dashboard

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/website#2390]
### Description

**Considerations:**
- Blog Tile

**Inspirations:**
- new Chart Types: Pie, Donut, Grouped Bar Charts, Stack Bar Charts

**Comment by Yndira-E** [comment]
Hi @joepavitt, here it is 🙂

![Image](https://github.com/user-attachments/assets/f0072bed-5451-4b16-ac75-24752930a7dc)
