### ISSUE TITLE
Blog Tile: Customise theming in your FlowFuse Dashboard

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#2411]
### Related Issue

https://github.com/FlowFuse/website/pull/2353

### Description

**Considerations:**
- Blog tile

**Comment by Yndira-E** [comment]
Hi @sumitshinde-84 here it is


![Image](https://github.com/user-attachments/assets/7e2e5596-4383-4d2f-a625-d26efd3ae39e)
