### ISSUE TITLE
Blog Art: Diagram illustrating the flow of data on the factory floor when bridging OPC UA to MQTT.

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#2436]
### Description

**Considerations:**
- Recreation of this diagram : https://raw.githubusercontent.com/FlowFuse/website/91e32a4971525ff75d9566420ea4d1e362a288f1/src/blog/2024/08/images/factory-floor-mqtt-opcua.png

**Content reference**
https://github.com/FlowFuse/website/pull/2431

**Comment by Yndira-E** [comment]
Hi @sumitshinde-84 


![Image](https://github.com/user-attachments/assets/f4f56a04-c64f-4d1a-a3d4-19708d61cdee)
