### ISSUE TITLE
Blog : Customise theming in your Node-RED Dashboard 2.0

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#2438]
### Related Issue

#2221

### Description

**Considerations:**
- Blog tile : Customise theming in your Node-RED Dashboard 2.0

**Content refernce:**
https://github.com/FlowFuse/website/pull/2353

**Comment by Yndira-E** [comment]
I'm closing this one as it seems to be a duplicate from [#2411](https://github.com/FlowFuse/website/issues/2411)
