### ISSUE TITLE
Add Gayan to team page

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/website#2449]
### Description

@gayanSandamal we have a [team page](https://flowfuse.com/team/) on our website, and you haven't been added yet. Could you please share a headshot (minimum 512px width) and provide the necessary information? I'm sharing mine as an example—just replace my info with yours. 😉

```
{
    "order": 11,
    "name": "Yndira Escobar",
    "title": "Visual Designer",
    "github": "Yndira-E",
    "linkedin": "yndira-escobar-es",
    "country": "ES",
    "email": "yndira@flowfuse.com",
    "headshot": "yndira.png",
    "facts": [
        "Over 15 years of experience in graphic design and art direction",
        "Successfully ran my own design studio for over five years",
        "Enjoy traveling to new places, exploring different cuisines, and indulging in my love for watching series"
    ]
}
```

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by gayanSandamal** [comment]
Hi @Yndira-E 

Thank you for sharing this with me 🙌 I hope the below information will help you.
I've attached a photograph of myself but please let me know if it's not working.
 
![gayan](https://github.com/user-attachments/assets/8a8d16a9-aca3-4bea-a28f-4af81125270c)


```
{
    "order": 11,
    "name": "Gayan Sandamal",
    "title": "Front End Engineer",
    "github": "gayanSandamal",
    "linkedin": "gayan-sandamal",
    "country": "LK",
    "email": "gayan@flowfuse.com",
    "headshot": "gayan.png",
    "facts": [
        "9+ years building large-scale enterprise web & mobile applications with the passion for UI/UX",
        "Produce music with friends for fun",
        "Enjoy meeting new people, watching the sunset over the ocean and love watching sci-fi and comedy movies"
    ]
}
```
