### ISSUE TITLE
Home page: industrial automation section

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/website#2480]
### Description

Add a section that describes the connect, collect, visualise and interact workflow.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
@ZJvandeWeg here's the version we discussed:

- Taking more vertical space
- Keeping both the image and the graphics
- I've also iterated on the dashboard graphics

Ideally, each card should link to a page. So far this is what I've thought:
1. Connect: https://flowfuse.com/solutions/device-management/
2. Collect: https://flowfuse.com/solutions/data-integration/
3. Visualise: https://flowfuse.com/product/dashboard/
4. Interact: Same as point 3? Any suggestions?

WDYT?

![Homepage - V7 0](https://github.com/user-attachments/assets/a7936a0f-d51c-4694-af41-cd69ff235978)

**Comment by ZJvandeWeg** [comment]
> Interact: Same as point 3? Any suggestions?

Dashboard is fine for now.
