### ISSUE TITLE
Blog tile and other graphics : Using MQTT Sparkplug B with Node-RED

### ISSUE THREAD

**Issue by sumitshinde-84** [FlowFuse/website#2487]
### Related Issue

https://github.com/FlowFuse/website/pull/2478

### Description

**Considerations:**
- Blog tile 
- Recreation of following image:
![Untitled-2023-12-06-1847](https://github.com/user-attachments/assets/21062216-fd87-4ea7-8e49-40c565f7ff77)
![sparkplug](https://github.com/user-attachments/assets/24496acd-1c75-4110-9e34-3b463dd047c9)

**Comment by Yndira-E** [comment]
Hi @sumitshinde-84 


![Image](https://github.com/user-attachments/assets/d10ba487-8cca-4ad1-bd45-7124f9efa0cc)
![Image](https://github.com/user-attachments/assets/cfcb10c7-ae98-4187-9702-63ab4c1d8e2c)
