### ISSUE TITLE
Blog: New Tab Layout, a Widget and Gauges are Available in FlowFuse Dashboard

### ISSUE THREAD

**Issue by gayanSandamal** [FlowFuse/website#2506]
### Description

New Tab Layout

<img width="445" alt="Screenshot 2024-08-28 at 12 07 06" src="https://github.com/user-attachments/assets/6b1cda5a-c198-420f-a07a-67aaf52b5169">

<img width="742" alt="layout-tab-dashboard" src="https://github.com/user-attachments/assets/ce89d17e-775f-4f4d-88d9-65edbe86f141">

New Widget: Input Number

<img width="187" alt="Screenshot 2024-08-28 at 12 07 52" src="https://github.com/user-attachments/assets/81a6d9ef-9712-4f6a-9eea-993efc98c2e3">

![image](https://github.com/user-attachments/assets/3e152cb8-9966-4bd2-9146-da4eb48b6030)

New Gauge: Battery

<img width="266" alt="Screenshot 2024-08-28 at 12 05 49" src="https://github.com/user-attachments/assets/9a2b7ff3-1a55-4e10-82eb-2f9e23ae2a85">

![image](https://github.com/user-attachments/assets/c696fc8a-d5dc-4c48-8674-72c3554972c1)

New Gauge: Tank Level

<img width="272" alt="Screenshot 2024-08-28 at 12 06 18" src="https://github.com/user-attachments/assets/9ff6312a-434b-4182-8b32-6bf196e5f244">

![image](https://github.com/user-attachments/assets/817c1661-1486-43c6-9acd-99715dd3f62b)

![image](https://github.com/user-attachments/assets/daa240df-b328-4154-865c-e8969184ab48)

<img width="279" alt="Screenshot 2024-08-28 at 11 50 24" src="https://github.com/user-attachments/assets/f533e60a-ec79-4638-a65f-a465cf0c0f1b">

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?

**Inspirations:**
- <link here>
- <link here>

**Comment by sumitshinde-84** [comment]
Assigning the issue to @joepavitt. He can handle the design work perfectly.

**Comment by joepavitt** [comment]
Already pushed to the branch:

![dashboard-2-1150-release](https://github.com/user-attachments/assets/92dc4c24-ea9f-4e0f-87a5-3e5fdb467e53)

**Comment by gayanSandamal** [comment]
> Already pushed to the branch:
> 
> ![dashboard-2-1150-release](https://private-user-images.githubusercontent.com/99246719/362249537-92dc4c24-ea9f-4e0f-87a5-3e5fdb467e53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDI1OTksIm5iZiI6MTcyNDg0MjI5OSwicGF0aCI6Ii85OTI0NjcxOS8zNjIyNDk1MzctOTJkYzRjMjQtZWE5Zi00ZTBmLTg3YTUtM2U1ZmRiNDY3ZTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDEwNTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMTU4NDU0MzE4ODQ0YWM2MWQwMDUxNDY2MjBkMGQxZDczMzZiMzBiNmQ5N2Q0YTU0MTdmM2VjMTI4ZTI5ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y7sxva_YtulibW0p-JuCRrAOujicZoIn9H_b6PuRfcE)

Thank you @joepavitt I will use it
