### ISSUE TITLE
Create FlowFuse for Education webpage

### ISSUE THREAD

**Issue by gstout52** [FlowFuse/website#2521]
### Description

**As an educator wanting to teach IoT, automation, ML, or other topics in engineering**

**I want to provide my students with access to FlowFuse**

**So that I can teach them Node-RED in the cloud and view their work from my FlowFuse team**

**Goal**: to increase FlowFuse user count by providing a free FlowFuse license for educational use.

**Plan**: Allow educators and their students to use FlowFuse Starter for free for the duration of an academic semester.

**Expected Impact**: 

- From January 1 - August 21, 2024 there have been 1,698 contacts created who selected Education. (By contrast, there have only been 639 for Business.)
- The conversion rate of users who sign up and select Education as their reason for joining have a very low self-serve conversion rate (0.53% year to date).
- However, by providing FlowFuse to university students we will create thousands of future FlowFuse champions in enterprises around the world.

**Implementation**:

For the first iteration, all we need is:

1. A new page on the website for education users
2. A HubSpot form for educators (to vet them)
3. Instructions for students on how to add their teacher to their Starter team, and for instructors on how to view students’ teams
4. A coupon code. (Website inspiration: https://tulip.co/education-partnerships/ )

Globally, there is no standard url that designates an academic institution, so for now we will manually vet applicants. Applications will be sent to me (Greg).

**Website Update:**

We will create a page on the website containing a signup form. The page will be linked under Resources in the top nav, and mentioned in the FAQ section on the main page.

**Website Copy:**

Header: FlowFuse for Education

FlowFuse is your partner in teaching engineering, IoT, development, OT/IT integration, and automation to your students. Free for educators and students. Contact us for an educational license.

[HubSpot form]

### Acceptance Criteria

- [ ] Create a FlowFuse for Education webpage. This can be used for inspiration: https://tulip.co/education-partnerships/ 
- [ ] Link to the FlowFuse for Education webpage under Resources in the top nav, and in the FAQ section on the main page
- [x] Create a HubSpot form for educators to reach out. (Greg will do this.)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by gstout52** [comment]
@ZJvandeWeg for visibility

**Comment by joepavitt** [comment]
Moving this over to @Yndira-E as it's website content and she'll be better placed to ensure design coherency

**Comment by Yndira-E** [comment]
Hi @gstout52 is there a document with the copy for this page?

**Comment by gstout52** [comment]
@Yndira-E Let's go with this:

Header: FlowFuse for Education

FlowFuse is your partner in teaching engineering, IoT, development, OT/IT integration, and automation to your students. Free for educators and students. Contact us for an educational license.

Hubspot form:
https://app-eu1.hubspot.com/submissions/26586079/form/48a92e16-8e5c-4bb6-aaee-ed0dfec0174d/performance?redirectUrl=https%3A%2F%2Fapp-eu1.hubspot.com%2Fforms%2F26586079%2F

**Comment by gstout52** [comment]
Looks good to me, @Yndira-E !
