### ISSUE TITLE
Q3 Website updates 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#2525]
### Description

Ideas to update the website to go along with the new messaging platform can be found on [this doc](https://docs.google.com/document/d/1c14U4Buoo0Xx-NmA98tMS_daEt1kVnb8PN5QKIeY3MY/edit)

thoughts welcome! 

@Yndira-E let me know if you have any questions. 

There's still more thinking to do be done for the features page. 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
V1 - Following the document step by step

![Image](https://github.com/user-attachments/assets/024afc14-c211-47c2-8cdf-655757e1fda0)

V2 - Changed/added some things:
- I moved the hero image to the second section; the concepts explained there correspond better with that graphic, and we can still add a video in the hero section.
- I added a space for numbers—just placeholders for now—but @robmarcer mentioned he could get some from clients. What do you think?
- I added images to the testimonials to make the page less abstract, but the I'm not sure the quote authors fit our ICP. There are no longer images of manufacturing environments.

![Image](https://github.com/user-attachments/assets/abd7c8a8-62a9-4de8-b0b1-797a58d7370a)

**Comment by Hasmin-AC** [comment]
I like V2! 

Hopefully we can get those stats in as it will make a great addition.

**Comment by MichaelBDavis** [comment]
Would be great to see a call-out box that addresses the concern we hear about Node-RED = prototyping tool
https://flowforgeworkspace.slack.com/archives/C02TG4WH5PC/p1724873712848749
https://flowforgeworkspace.slack.com/archives/C02TG4WH5PC/p1724860192391489

**Comment by ZJvandeWeg** [comment]
@MichaelBDavis What did you have in mind? "Explore how to promote Node-RED to Production" at the end instead of: "Explore more about FlowFuse and Node-RED"?
