### ISSUE TITLE
Waiting room video for Zoom webinars 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#2547]
### Description

I'd like to add a short video about FF while people are in the waiting room before a webinar starts. An animated version of the FF circle with the tag line "The Fastest Way to Build and Operate Industrial Data Solutions" and the text  at the bottom  "The webinar will start shortly" 

Here are the basic specs provided for it - Up to 30 MB of MP4, MOV, or M4V files

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC how about an image as a first iteration?

**Comment by Yndira-E** [comment]
I wasn't sure about the size, but since the usual screen size is 1920x1080px, I went with that. Please test it and let me know if it looks good!

![Image](https://github.com/user-attachments/assets/4db9dd1c-fa44-4cd8-bac0-4dba10ea5144)

**Comment by Hasmin-AC** [comment]
The specs for image is as follows - A minimum width of 400px and height of 200px (ratio of width to height is suggested to be 2:1)

I tried resizing but the quality dropped. Let me know if you are able to resend. thanks!

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC if you resize it as a JPG it would distort the image as it didn't have the right proportion.

I've edited it, here it is at 2:1 ratio ;) 

![Image](https://github.com/user-attachments/assets/7301119c-d90f-4494-92cd-59df1dcf4b87)

**Comment by Hasmin-AC** [comment]
Thanks @Yndira-E I've uploaded it to the waiting room settings.

**Comment by Hasmin-AC** [comment]
there's just the option to upload video. We'll have to see how it goes tomorrow.
