### ISSUE TITLE
Remove Project Nodes from Main menu

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#2548]
### Description

Following a discussion with ZJ, it was decided its best to take off project nodes as a high level menu item. 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC, just for the sake of keeping everything documented, would you mind sharing the reasoning behind this decision here? Thanks in advance!
