### ISSUE TITLE
Features page update

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/website#2555]
### Description

[Copy in this doc](https://docs.google.com/document/d/1c14U4Buoo0Xx-NmA98tMS_daEt1kVnb8PN5QKIeY3MY/edit)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC,

I’m not sure about the main image. I chose that one because it showcases the low-code platform (Node-RED) along with the immersive editor and FlowFuse tools for that instance, all in a single image.

I tried using the original photos for the "connect, collect..." section, but it felt overwhelming and made the page longer. For the features page, it didn’t feel as appropriate as it did on the homepage. I think it’s more balanced this way.

Since the new messaging, where we refer more specifically to industrial data, we’ve moved away from the 'hard hats' images.

I’ve rearranged the features in the last section to group the ones with videos, as it looked messy otherwise. Will we be creating videos for all the features?

This is an iteration, and we’ll add the form in the next one. I’ve added a comment to the document regarding that.

Let me know your thoughts!

![Image](https://github.com/user-attachments/assets/597e1560-34d0-428e-b8fa-b660732c08a4)

**Comment by Hasmin-AC** [comment]
Hi @Yndira-E 

How about we add the "Download Platform Overview" and "Contact us" buttons at the top, right under the opening paragraph? 

I would add the Node-RED logo to the Low-Code Development Section rather than the. FlowFuse Section. 

Maybe lets drop the videos and have only icons for all? Those videos are a bit old anyway and show older versions of the product. 

Other than that looks great!

**Comment by Yndira-E** [comment]
> How about we add the "Download Platform Overview" and "Contact us" buttons at the top, right under the opening paragraph?

I agree. I was going to add the button to the form there when we had it. And yes, a CTA to contact us would be a natural next step. I meant to bring it up, but I forgot to mention that we were removing the last section we currently have with that kind of CTA.

> I would add the Node-RED logo to the Low-Code Development Section rather than the FlowFuse Section.

Sure, I'll change it. I actually added it there first, but then noticed that `Node-RED` was part of the title of the following section, so I moved it.

> Maybe let's drop the videos and have only icons for all? Those videos are a bit old anyway and show older versions of the product.

Ok, this will make it look more consistent.

**Comment by Yndira-E** [comment]
Here's the updated version.

I've also added some links to some of the features. Let me know if there are other pages related to the remaining features that can be linked.

![Image](https://github.com/user-attachments/assets/7f3b3950-ab5d-4470-aec0-b7e21b295f45)

And @joepavitt, I'd like your input on the hero section image. Maybe it could be something animated (for a future iteration) or a screen recording? What do you think could highlight the most popular features in about 5 seconds?

Also, I'll change the name of the instance, but is there any information in that image that should be removed due to sensitivity?

**Comment by Hasmin-AC** [comment]
Looks good to go @Yndira-E. Lets link to Node-RED page. I'll look for any other blogs and add to PR when ready. Thanks!
