### ISSUE TITLE
FF Platform Overview Download 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#2564]
### Description

Here's the [content for the FF Platform Overview ](https://docs.google.com/document/d/1i_VrLjDIZZkSur4o0sd5cmEwNtXWzL5gmKPaGHe3adI/edit) downloadable PDF for design and layout. This will be placed as the CTA in the Features Page behind a form. 

@joepavitt please review features and add any other key aspect that's missing. 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC here's the [styled google doc](https://docs.google.com/document/d/1VtLQMZvvGDqTjiplUoUtdLwEeS9W5F7Y-42N2zGmRFc/edit?usp=sharing). I didn't include the last part, `Why Enterprises Choose FlowFuse`, as it didn't seem to be ready, and you mentioned it could be added later

**Comment by Hasmin-AC** [comment]
Thanks @Yndira-E Here's the form ID to download - "93ddc751-741d-4997-a22a-c05548a0a698"
Right now it takes you to a thank you message but I did create a thank you page for your review https://github.com/FlowFuse/website/pull/2595. Will update form when page is published. 

Looks like the pop-up form option is not available on HS any more so we'll have to code it or place it as an expansion on the button click.
