### ISSUE TITLE
Improve Search on Website

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/website#2630]
### Description

We are using Algolia for search, it was built as a quick iteration, that we've never really re-visited.

The search bar is the most interacted with element in our docs, but the search results are terrible, this task is to track improvements in this space.

In particular, I think the following tasks should be considered:

- [ ] Separate `docs` out such that searching when in the scope of `/docs` only returns `docs` items. Or at least, prioritises documentation content. It should definitely _not_ return Handbook content
- [ ] Searching in our Handbook should just return `/handbook` content
- [ ] On mobile, the search is very broken, if you type a couple of characters, they then get auto-deleted, this needs investigation.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hi @joepavitt thanks for the issue, I already had one created: https://github.com/FlowFuse/website/issues/2314 I'll delete it since it's duplicated now.

I did investigate a bit, but couldn't find many built in options since we're using the netlify free plugin. Maybe some extra coding would get us what we want!

**Comment by joepavitt** [comment]
For me, Android/Chrome - every 2-3 characters I type, it clears the search

**Comment by Yndira-E** [comment]
Mmm... That's odd, I've just tried from an Android and it works too
<img src="https://github.com/user-attachments/assets/49376c78-355b-4cdb-a38b-3d36ca76c48b" width="300"/>

**Comment by cstns** [comment]
The best approach would be to namespace search queries.

This would imply adding a new 'namespace' attribute that algolia tracks in the header section of each doc. Namespace values could be docs/userDocs, handbook etc.

From what I can tell we're initializing algolia's search bar in a lot of places, so we can just add a new `searchParameters.filters = 'namespace:handbook'` where needed

**Comment by joepavitt** [comment]
Sounds good to me @cstns - we are also currently using [Netlify's Algolia plugin](https://www.algolia.com/doc/tools/crawler/netlify-plugin/quick-start/), but we may want to switch to the standard option of [InstantSearchJS](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/)
