### ISSUE TITLE
Update the website for the MQTT offering

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/website#2665]
### Description

As we're approaching the MQTT offering launch date we should investigate what we need to change on the marketing website to inform our users.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by gstout52** [comment]
- Include mention in Enterprise area and feature comparison listIng on pricing page https://flowfuse.com/pricing/
- On features page, maybe in the Remote Device Management at the Edge section https://flowfuse.com/product/features/ 
- On the Device Management page https://flowfuse.com/solutions/device-management/
- In the "FlowFuse Extras" section in our docs https://flowfuse.com/docs/

**Comment by gstout52** [comment]
***Legal terms***

Subscription Agreement 1.4:
- No revision is needed to this agreement, as the definition of "software" in the agreement should cover the MQTT broker service. 
"'Software' means software, and other branded offerings made available by FlowFuse or its Affiliate(s), including but not limited to, FlowFuse’s Application Platform."


Flowfuse.com/terms:
- Section 2.2 may need to be revised to mention the broker service here. "The Administrative User shall, among other things, have the ability to create and manage teams and projects [AND THE BROKER SERVICE], add new Registered Users and control settings and permissions for Registered Users..."
- Section 4.2(e) may or may not need a 'fair use' provision added here. "Customer will not, and will not permit any Authorized User or other party to...(e) interfere in any manner with the operation of the SaaS Services or the hardware and network used to operate the SaaS Services..." My reason for thinking we could need a 'fair use' provision is that misuse of the broker service could cause the service crash for all FlowFuse customers.

**Comment by ZJvandeWeg** [comment]
The standard terms are both alright @gstout52, no need to update them for FFC. It seems that on the legal side we're good to go to offer the broker.
