### ISSUE TITLE
Updates to "About FlowForge" page

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/website#267]
### Description

Exact design/layout still be worked on

### Acceptance Criteria

- [x] Include FlowForge timeline/roadmap: #194 
- [ ] Remove the "Working at FlowForge" sections, as that's now in the "Team" page
- [ ] Add FAQs (may want to reference these elsewhere too, or make the "About" page more acessible, rather than just in the footer)

**Comment by ZJvandeWeg** [comment]
Adding investors for credibility is something I'd add too

**Comment by joepavitt** [comment]
Closed - efforts moved to https://github.com/flowforge/website/issues/798
