### ISSUE TITLE
Landing page for low code whitepaper 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#2735]
### Description

@yndira can you please create a landing page for the low code whitepaper with the content found on [this doc.](https://docs.google.com/document/d/1890KwqWYjZNvgtkrsUhT_BCUd1J8fbz7fh6i0ghoCiw/edit?tab=t.0) 
This will be the landing page for LinkedIn ads. 
thanks! 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
Hey @Hasmin-AC, reading through the document, I realize this one differs from the other white papers we’ve created. Just to clarify, aren’t we adding the content from the white paper to this page?

And will there be more like this in the future? I’m asking so I know if I should create a new template or if this is just a one-time thing.

**Comment by Hasmin-AC** [comment]
Yes this is different as its more of a promotional landing page. We can template it and use this style again if its showing good engagement.

**Comment by Yndira-E** [comment]
Ok, what about the URL? should it be `/landing/...` or `/whitepaper/...`
Also, since you'll be using it for the paid campaign, should we prevent it from being indexed by search engines?

**Comment by Hasmin-AC** [comment]
URL should be /landing/
its alright for the page to be crawled.

**Comment by Yndira-E** [comment]
Is something like this what you had in mind?
![Image](https://github.com/user-attachments/assets/cc450ac5-ceac-4a80-b8cb-b04318031d16)

**Comment by Yndira-E** [comment]
And the URL, should it be `/landing/Accelerating-Industrial-Innovation-With-Low-Code-Platforms`?

**Comment by Hasmin-AC** [comment]
I think a more prominent header banner and image with the download form moved down would be better. Align the form more with the second section.

**Comment by Yndira-E** [comment]
Ok, something like then
![Image](https://github.com/user-attachments/assets/78efbde7-2342-4028-9967-0e8c2bc6aa50)

**Comment by Hasmin-AC** [comment]
Looks good. Lets try it out. thanks
