### ISSUE TITLE
Update "Licensed Node-RED instances" field on Request a Quote Page

### ISSUE THREAD

**Issue by MichaelBDavis** [FlowFuse/website#2741]
### Description

Since we are now packaging a starting capacity of 20 instances in the Enterprise edition, we could change this field from "Licensed Node-RED instances" to "Expected Node-RED instances" and add the information that the Enterprise edition comes with a starting capacity of 20 instances. 
https://flowfuse.com/pricing/request-quote/

**Comment by Yndira-E** [comment]
Hi @MichaelBDavis! I think you might be able to make this change on your own—it’s a HubSpot form, so you should be able to edit it directly in HubSpot.
