### ISSUE TITLE
Social Post: Install Time Improvements

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/website#2743]
### Related Issue

Title:
Installing FlowFuse just got 3x faster

before: 555s
after: 166s

### Description

**Considerations:**
- Social Post

**Inspirations:**
- https://github.com/FlowFuse/flowfuse/issues/4573#issuecomment-2455185388

Want to shout about how we've made improvements in the onboarding/installing time, @ZJvandeWeg mentioned we could do a single graphic to do a social post

Clear "before"/after is the message that needs communicating, could do a vertical Sankey diagram type image?

**Comment by Yndira-E** [comment]
Hi @joepavitt 
is this something like what you had in mind?
![Image](https://github.com/user-attachments/assets/0bce00d6-92d1-4349-87dc-c56ebf3aec2e)

**Comment by joepavitt** [comment]
It is, although I think the title needs to be brighter, and the 555/166 can be written as `Xm Ys` instead to make it easier to read - maybe even a little larger too?

**Comment by Yndira-E** [comment]
![Image](https://github.com/user-attachments/assets/dc7e4f41-423a-4ef3-8c03-185ad36b91a1)

**Comment by Yndira-E** [comment]
And for the description:

> 🚀 Installing FlowFuse just got 3x faster!
> 
> Our latest update has reduced installation times, cutting them down from over 9 minutes to under 3 minutes. This means you can start working with FlowFuse without delays and with a much smoother setup process.
> 
> Interested in giving it a try? Check out the complete installation guide to set up FlowFuse in your Docker environment and get started in minutes.
> 
> 🔗 https://flowfuse.com/docs/install/docker/
> 
> #FlowFuse #NodeRED #IIoT #Automation #Docker

WDYT?

**Comment by joepavitt** [comment]
> you can start working with Self-Hosted FlowFuse with

Added in "Self Hosted", just to stress that this is for self-hosted installs. FF Cloud getting started times is seconds

**Comment by Yndira-E** [comment]
Done. I've scheduled it for tomorrow.
