### ISSUE TITLE
Create sub menu item "eBooks and Whitepapers" 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/website#2773]
### Description

Now that we have about 5 ebooks and whitepapers in total it would be good to have a landing page which lists them all for easy access.  
I suggest having a sub menu item called "eBooks & White papers" listed under Resources. 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-E** [comment]
@Hasmin-AC, here’s the preview of the page. It will be ordered chronologically, so the final result might not look exactly like this. I’ll work on the development next week.
![Image](https://github.com/user-attachments/assets/bc0c5249-5f8e-4dd1-852f-27e3c15b9cd5)

**Comment by Hasmin-AC** [comment]
Looks good Yndira. I don't think we really need the description though. Can we skip that part?

**Comment by Hasmin-AC** [comment]
I don't see an issue with not having a description. But if you think its necessary maybe something like the following can be added
"Ready to dive deeper into the world of FlowFuse? Browse our library of whitepapers and ebooks and discover the power of our low-code industrial data platform.
