### ISSUE TITLE
New Opto22 customer story

### ISSUE THREAD

**Issue by iskerrett** [FlowFuse/website#807]
### Description

We need to publish a new customer story from Node-RED.  I have created a branch but it doesn't show up on the main customer story page. Not sure what I need to do?  

I also need to ask Opto 22 for a graphic.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by iskerrett** [comment]
I included in the Development box but here it is again. https://github.com/flowforge/website/tree/optp22-node-red-story

**Comment by iskerrett** [comment]
Yrinda, helped me get this working. I needed to restart the local server.

**Comment by iskerrett** [comment]
I still need to get an image from Opto 22.

**Comment by iskerrett** [comment]
Here is the image from Opto22.

![Image4-FlowForge_CaseStudy](https://github.com/flowforge/website/assets/36051834/97f5d5c0-4c29-44b7-8744-f9d82a915510)

**Comment by iskerrett** [comment]
@Yndira-FlowForge just making sure you see that Opto22 has sent the graphic for their story.

**Comment by Yndira-FlowForge** [comment]
Hi @iskerrett I didn't get a notification, thanks for telling me
